import { ApiError, Avatar, Badge, Card, CardBody, EmptyState, Page, PageBody, PageHeader, QueryBoundary, api, useQuery, formatCompact, cn, type FeedbackItem } from "@hubchat/shared";
import { ChevronUp, FileQuestion, MessageSquare } from "lucide-react";
import { Link } from "react-router-dom";
import { STATUS_META } from "./BoardDetail";

const COLUMNS = ["planned", "in_progress", "completed"];

export default function Roadmap() {
  const query = useQuery<{ data: FeedbackItem[] }>(["feedback-roadmap"], (signal) => api.get("/feedback/roadmap", { signal }));
  return <Page><PageHeader title="Roadmap" description="A live view of what is planned, in progress, and shipped." /><PageBody width="full"><QueryBoundary query={query}>{() => <>{query.error instanceof ApiError && <p className="mb-4 text-sm text-danger">{query.error.message}</p>}<div className="grid gap-4 lg:grid-cols-3">{COLUMNS.map((column) => { const meta = STATUS_META[column]!; const items = (query.data?.data ?? []).filter((item) => item.status === column); return <section key={column} className="flex min-w-0 flex-col"><header className="mb-3 flex items-center gap-2"><Badge tone={meta.tone} dot>{meta.label}</Badge><span className="text-xs tabular text-fg-muted">{items.length}</span></header><div className="flex flex-col gap-2">{items.map((item) => <Card key={item.id} interactive className="p-0"><Link to={`/feedback/items/${item.id}`} className="block"><CardBody className="p-3"><p className="text-sm font-medium leading-snug text-fg">{item.title}</p>{item.description && <p className="mt-1 line-clamp-2 text-xs leading-normal text-fg-muted">{item.description}</p>}<div className="mt-2.5 flex items-center gap-3 text-2xs text-fg-muted"><span className={cn("flex items-center gap-1 rounded-sm bg-fill px-1.5 py-0.5 tabular text-fg-secondary")}><ChevronUp className="size-3" />{formatCompact(item.vote_count)}</span><span className="flex items-center gap-1"><MessageSquare className="size-3" />{item.comment_count}</span>{item.submitter_id && <span className="ml-auto"><Avatar name={item.submitter_id} seed={item.submitter_id} size="2xs" /></span>}</div></CardBody></Link></Card>)}{items.length === 0 && <p className="rounded-lg border border-dashed border-line px-3 py-8 text-center text-xs text-fg-muted">Nothing here yet</p>}</div></section>; })}</div>{(query.data?.data ?? []).length === 0 && <EmptyState icon={FileQuestion} title="No public roadmap items" description="Publish feedback items to show them here." />}</>}</QueryBoundary></PageBody></Page>;
}
