import type { PortalBootstrap } from "./portal-context";

type MessageTable = Record<string, string>;

const messages: Record<string, MessageTable> = {
  en: {
    loading_portal: "Loading portal…",
    try_again: "Try again",
    skip_to_content: "Skip to content",
    portal_navigation: "Portal",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    match_system: "Match system",
    my_requests: "My requests",
    profile_preferences: "Profile & preferences",
    sign_in: "Sign in",
    sign_out: "Sign out",
    search_guides: "Search guides and answers…",
    search_help_centre: "Search the help centre",
    help_centre_unavailable: "Help centre unavailable.",
    nothing_matches: "Nothing matches “{query}”",
    try_fewer_words: "Try fewer words, or",
    send_us_request: "send us a request",
    contact_team: "contact the team",
    use_links_support: "Use the links above to find support or contact the team.",
    latest_guides: "Latest guides",
    browse_all: "Browse all",
    loading_guides: "Loading guides…",
    guides_unavailable: "Guides unavailable",
    no_guides: "No published guides yet",
    most_read: "Most read",
    views: "{count} views",
    still_need_help: "Still need help?",
    send_request: "Send a request",
    reply_business_day: "We reply within one business day, usually much sooner.",
    suggest_improvement: "Suggest an improvement",
    vote_build: "Vote on what we build next, or add something we have missed.",
    all_guides: "All guides",
    search_published_help: "Search the published help centre.",
    search_all_guides: "Search all guides",
    no_articles_match: "No articles match",
    guides_loaded: "{count} guide{suffix} loaded",
    browse_all_guides: "Browse all guides",
    your_requests: "Your requests",
    requests_description: "Everything you have sent us, and where it stands.",
    new_request: "New request",
    filter_requests: "Filter requests",
    open: "Open",
    all: "All",
    no_requests: "No requests here",
    follow_requests: "When you send us something, it appears here so you can follow along.",
    requests_loaded: "{count} request{suffix} loaded",
    no_description: "No description provided.",
    updated: "updated {time} ago",
    check_email: "Check your email",
    sent_sign_in: "We sent a sign-in link to your address. It works once and expires in 15 minutes.",
    different_email: "Use a different email",
    sign_in_subtitle: "To view your requests and follow feedback.",
    anonymised: "Your profile has been anonymised and all portal sessions were revoked.",
    email: "Email",
    sending: "Sending…",
    email_sign_in: "Email me a sign-in link",
    could_not_send: "Could not send the sign-in link.",
    or: "or",
    no_account: "You do not need an account to send a request —",
    submit_here: "submit one here",
    reply_by_email: "and we will reply by email.",
  },
  fr: {
    loading_portal: "Chargement du portail…", try_again: "Réessayer", skip_to_content: "Aller au contenu",
    portal_navigation: "Portail", appearance: "Apparence", light: "Clair", dark: "Sombre", match_system: "Selon le système",
    my_requests: "Mes demandes", profile_preferences: "Profil et préférences", sign_in: "Se connecter", sign_out: "Se déconnecter",
    search_guides: "Rechercher des guides et des réponses…", search_help_centre: "Rechercher dans l’aide",
    help_centre_unavailable: "Centre d’aide indisponible.", nothing_matches: "Aucun résultat pour « {query} »", try_fewer_words: "Essayez moins de mots, ou",
    send_us_request: "envoyez-nous une demande", contact_team: "contactez l’équipe", use_links_support: "Utilisez les liens ci-dessus pour obtenir de l’aide ou contacter l’équipe.",
    latest_guides: "Derniers guides", browse_all: "Tout afficher", loading_guides: "Chargement des guides…", guides_unavailable: "Guides indisponibles", no_guides: "Aucun guide publié pour le moment", most_read: "Les plus consultés", views: "{count} vues",
    still_need_help: "Besoin d’aide ?", send_request: "Envoyer une demande", reply_business_day: "Nous répondons sous un jour ouvré, généralement plus vite.", suggest_improvement: "Suggérer une amélioration", vote_build: "Votez pour nos prochaines évolutions ou ajoutez une idée.",
    all_guides: "Tous les guides", search_published_help: "Rechercher dans l’aide publiée.", search_all_guides: "Rechercher dans tous les guides", no_articles_match: "Aucun article correspondant", guides_loaded: "{count} guide{suffix} chargé{suffix}", browse_all_guides: "Voir tous les guides",
    your_requests: "Vos demandes", requests_description: "Tout ce que vous nous avez envoyé et son état.", new_request: "Nouvelle demande", filter_requests: "Filtrer les demandes", open: "Ouvertes", all: "Toutes", no_requests: "Aucune demande ici", follow_requests: "Vos demandes apparaîtront ici pour vous permettre de les suivre.", requests_loaded: "{count} demande{suffix} chargée{suffix}", no_description: "Aucune description.", updated: "mis à jour il y a {time}",
    check_email: "Consultez votre e-mail", sent_sign_in: "Nous avons envoyé un lien de connexion. Il est utilisable une fois et expire dans 15 minutes.", different_email: "Utiliser une autre adresse", sign_in_subtitle: "Pour consulter vos demandes et suivre les retours.", anonymised: "Votre profil a été anonymisé et toutes vos sessions ont été révoquées.", email: "E-mail", sending: "Envoi…", email_sign_in: "M’envoyer un lien de connexion", could_not_send: "Impossible d’envoyer le lien de connexion.", or: "ou", no_account: "Vous n’avez pas besoin de compte pour envoyer une demande —", submit_here: "envoyez-en une ici", reply_by_email: "et nous vous répondrons par e-mail.",
  },
  es: {
    loading_portal: "Cargando portal…", try_again: "Reintentar", skip_to_content: "Ir al contenido", portal_navigation: "Portal", appearance: "Apariencia", light: "Claro", dark: "Oscuro", match_system: "Según el sistema", my_requests: "Mis solicitudes", profile_preferences: "Perfil y preferencias", sign_in: "Iniciar sesión", sign_out: "Cerrar sesión", search_guides: "Buscar guías y respuestas…", search_help_centre: "Buscar en el centro de ayuda", help_centre_unavailable: "Centro de ayuda no disponible.", nothing_matches: "No hay coincidencias para «{query}»", try_fewer_words: "Prueba con menos palabras o", send_us_request: "envíanos una solicitud", contact_team: "contacta con el equipo", use_links_support: "Usa los enlaces anteriores para obtener ayuda o contactar con el equipo.", latest_guides: "Últimas guías", browse_all: "Ver todas", loading_guides: "Cargando guías…", guides_unavailable: "Guías no disponibles", no_guides: "Aún no hay guías publicadas", most_read: "Más leídas", views: "{count} visitas", still_need_help: "¿Aún necesitas ayuda?", send_request: "Enviar una solicitud", reply_business_day: "Respondemos en un día laborable, normalmente antes.", suggest_improvement: "Sugerir una mejora", vote_build: "Vota por lo que construiremos o añade algo que falte.", all_guides: "Todas las guías", search_published_help: "Busca en el centro de ayuda publicado.", search_all_guides: "Buscar en todas las guías", no_articles_match: "Ningún artículo coincide", guides_loaded: "{count} guía{suffix} cargada{suffix}", browse_all_guides: "Ver todas las guías", your_requests: "Tus solicitudes", requests_description: "Todo lo que nos has enviado y su estado.", new_request: "Nueva solicitud", filter_requests: "Filtrar solicitudes", open: "Abiertas", all: "Todas", no_requests: "No hay solicitudes", follow_requests: "Tus solicitudes aparecerán aquí para que puedas seguirlas.", requests_loaded: "{count} solicitud{suffix} cargada{suffix}", no_description: "Sin descripción.", updated: "actualizada hace {time}", check_email: "Revisa tu correo", sent_sign_in: "Enviamos un enlace de acceso. Funciona una vez y caduca en 15 minutos.", different_email: "Usar otro correo", sign_in_subtitle: "Para ver tus solicitudes y seguir los comentarios.", anonymised: "Tu perfil se ha anonimizado y se han revocado todas las sesiones.", email: "Correo electrónico", sending: "Enviando…", email_sign_in: "Enviarme un enlace de acceso", could_not_send: "No se pudo enviar el enlace de acceso.", or: "o", no_account: "No necesitas una cuenta para enviar una solicitud —", submit_here: "envíala aquí", reply_by_email: "y te responderemos por correo.",
  },
  ar: {
    loading_portal: "جار تحميل البوابة…", try_again: "حاول مرة أخرى", skip_to_content: "انتقل إلى المحتوى", portal_navigation: "البوابة", appearance: "المظهر", light: "فاتح", dark: "داكن", match_system: "مطابقة النظام", my_requests: "طلباتي", profile_preferences: "الملف الشخصي والتفضيلات", sign_in: "تسجيل الدخول", sign_out: "تسجيل الخروج", search_guides: "ابحث عن الأدلة والإجابات…", search_help_centre: "ابحث في مركز المساعدة", help_centre_unavailable: "مركز المساعدة غير متاح.", nothing_matches: "لا توجد نتائج لـ «{query}»", try_fewer_words: "جرّب كلمات أقل، أو", send_us_request: "أرسل طلبًا إلينا", contact_team: "تواصل مع الفريق", use_links_support: "استخدم الروابط أعلاه للحصول على المساعدة أو للتواصل مع الفريق.", latest_guides: "أحدث الأدلة", browse_all: "عرض الكل", loading_guides: "جار تحميل الأدلة…", guides_unavailable: "الأدلة غير متاحة", no_guides: "لا توجد أدلة منشورة بعد", most_read: "الأكثر قراءة", views: "{count} مشاهدة", still_need_help: "هل ما زلت بحاجة إلى المساعدة؟", send_request: "إرسال طلب", reply_business_day: "نرد خلال يوم عمل واحد، وغالبًا أسرع.", suggest_improvement: "اقترح تحسينًا", vote_build: "صوّت لما سنبنيه لاحقًا أو أضف ما ينقصنا.", all_guides: "كل الأدلة", search_published_help: "ابحث في مركز المساعدة المنشور.", search_all_guides: "ابحث في كل الأدلة", no_articles_match: "لا توجد مقالات مطابقة", guides_loaded: "تم تحميل {count} دليل", browse_all_guides: "عرض كل الأدلة", your_requests: "طلباتي", requests_description: "كل ما أرسلته إلينا وحالته.", new_request: "طلب جديد", filter_requests: "تصفية الطلبات", open: "مفتوحة", all: "الكل", no_requests: "لا توجد طلبات هنا", follow_requests: "ستظهر طلباتك هنا لتتمكن من متابعتها.", requests_loaded: "تم تحميل {count} طلب", no_description: "لا يوجد وصف.", updated: "تم التحديث قبل {time}", check_email: "تحقق من بريدك الإلكتروني", sent_sign_in: "أرسلنا رابط تسجيل الدخول. يعمل مرة واحدة وتنتهي صلاحيته خلال 15 دقيقة.", different_email: "استخدم بريدًا آخر", sign_in_subtitle: "لعرض طلباتك ومتابعة الملاحظات.", anonymised: "تم إخفاء هوية ملفك الشخصي وإلغاء جميع جلسات البوابة.", email: "البريد الإلكتروني", sending: "جار الإرسال…", email_sign_in: "أرسل لي رابط تسجيل الدخول", could_not_send: "تعذر إرسال رابط تسجيل الدخول.", or: "أو", no_account: "لا تحتاج إلى حساب لإرسال طلب —", submit_here: "أرسله هنا", reply_by_email: "وسنرد عليك عبر البريد الإلكتروني.",
  },
};

// The core dictionary above covers the shell and first-run journeys. These
// supplemental entries keep the deeper self-service pages localized without
// duplicating the large fallback table; missing keys still deliberately fall
// back to the supplied English copy.
const supplementalMessages: Record<string, MessageTable> = {
  fr: {
    loading_article: "Chargement de l’article…", article_not_found: "Article introuvable", article_unpublished: "Il a peut-être été déplacé ou dépublié.", updated_date: "Mis à jour le {date}", article_feedback_thanks: "Merci — votre retour est transmis à la personne qui gère cette page.", was_helpful: "Cet article vous a-t-il aidé ?", yes: "Oui", no: "Non", helpful_count: "{count} personne(s) ont trouvé cela utile", anything_add: "Quelque chose à ajouter ? (facultatif)", what_looking: "Que recherchiez-vous ?", article_feedback: "Retour sur l’article", send_feedback: "Envoyer le retour", feedback_error: "Impossible d’enregistrer le retour. Réessayez.", back_to_guides: "Retour aux guides", article_not_answer: "Cela ne répond pas à ma question",
    changelog: "Nouveautés", changelog_description: "Ce que nous avons livré, du plus récent au plus ancien.", subscription_settings: "Paramètres d’abonnement", loading_updates: "Chargement des nouveautés…", changelog_unavailable: "Nouveautés indisponibles", no_updates: "Aucune nouveauté publiée", check_updates: "Revenez ici pour découvrir les mises à jour.", updates_loaded: "{count} mise(s) à jour chargée(s)",
    loading_feedback: "Chargement des retours…", feedback_unavailable: "Retours indisponibles", no_feedback_board: "Aucun tableau de retours", no_feedback_board_description: "Aucun tableau public n’est configuré pour ce portail.", feedback_description: "Votez pour ce qui compte pour vous. Les abonnés sont informés des évolutions.", suggest_something: "Suggérer quelque chose", suggest_description: "Décrivez le problème rencontré pour aider l’équipe à le comprendre.", cancel: "Annuler", submit: "Envoyer", title: "Titre", what_trying: "Que cherchez-vous à faire ?", submit_feedback_error: "Impossible d’envoyer cette suggestion. Réessayez.", view: "Vue", top_voted: "Les plus votées", roadmap: "Feuille de route", search_feedback: "Rechercher dans les retours", loading_ideas: "Chargement des idées…", ideas_unavailable: "Impossible de charger les idées", no_ideas_match: "Aucune idée correspondante", suggest_first: "Essayez une autre recherche ou suggérez la première idée.", nothing_here: "Rien ici pour le moment", ideas_loaded: "{count} idée(s) chargée(s)",
    loading_feedback_item: "Chargement du retour…", feedback_item_unavailable: "Retour indisponible", feedback_item_private: "Cette demande a peut-être été supprimée ou n’est pas publique.", back_to_feedback: "Retour aux retours", submitted_date: "Envoyé le {date}", no_description: "Aucune description.", votes: "{count} vote(s)", comments: "{count} commentaire(s)", discussion: "Discussion", loading_comments: "Chargement des commentaires…", comments_error: "Impossible de charger les commentaires. Réessayez.", no_comments: "Aucun commentaire pour le moment.", customer: "Client", comments_loaded: "{count} commentaire(s) chargé(s)", add_discussion: "Ajouter à la discussion…", sign_in_comment: "Connectez-vous pour commenter cette demande.", post_comment_error: "Impossible de publier le commentaire. Réessayez.", post_comment: "Publier le commentaire", sign_in_comment_link: "Se connecter pour commenter",
    loading_forms: "Chargement des formulaires…", forms_unavailable: "Formulaires indisponibles", forms: "Formulaires", contact_forms: "Formulaires de contact", choose_form: "Choisissez le formulaire qui correspond le mieux à votre besoin.", no_forms: "Aucun formulaire disponible", no_forms_description: "Aucun formulaire publié ici pour le moment.", sign_in_required: "Connexion requise", loading_form: "Chargement du formulaire…", sign_in_use_form: "Connectez-vous pour utiliser ce formulaire", form_authenticated: "Ce formulaire est réservé aux clients connectés.", form_unavailable: "Formulaire indisponible", form_not_found: "Formulaire introuvable", form_unpublished: "Ce formulaire a peut-être été dépublié.", back_to_forms: "Retour aux formulaires", response_received: "Réponse reçue",
    loading_survey: "Chargement du questionnaire…", survey_unavailable: "Questionnaire indisponible", survey_expired: "Ce questionnaire a peut-être expiré ou été supprimé.", survey_thanks: "Merci pour votre retour. Votre réponse a été enregistrée.", thank_you: "Merci", survey_intro: "Une courte question sur votre expérience d’assistance.", choose_one: "Choisissez…", survey_submit_error: "Impossible d’enregistrer votre réponse. Réessayez.", submit_response: "Envoyer la réponse",
    sign_in_before_request: "Connectez-vous avant d’envoyer une demande", session_request_history: "Une session de portail relie votre historique et vos réponses à votre compte.", thanks_on_it: "Merci — nous nous en occupons", request_created: "Votre demande est", view_request: "Voir la demande", back_help_centre: "Retour au centre d’aide", attachment_upload_warning: "La demande a été créée, mais certaines pièces jointes n’ont pas pu être envoyées.", specific_help: "Plus votre demande est précise, plus nous pouvons vous aider rapidement.", help_subject: "De quoi avez-vous besoin ?", one_line: "Une ligne suffit ; vous pouvez ajouter des détails ci-dessous.", tell_more: "Dites-nous en plus", expected_happened: "Ce que vous attendiez, ce qui s’est passé et quand.", urgency: "Quel est le niveau d’urgence ?", severity: "Urgence", blocking: "Bloquant", cannot_work: "Nous ne pouvons plus travailler.", major: "Majeur", core_broken: "Une fonction essentielle est en panne.", minor: "Mineur", annoying_continue: "Gênant, mais nous pouvons continuer.", question: "Simple question", your_email: "Votre e-mail", reply_here: "Nous répondrons ici.", attachments: "Pièces jointes", attachment_description: "Captures, journaux ou enregistrement d’écran. 25 Mo maximum par fichier.", choose_attachments: "Choisir des captures ou journaux", browse_guides_instead: "Voir plutôt les guides", request_error: "Impossible d’envoyer la demande. Votre brouillon est conservé.", suggested_guides: "Ces guides peuvent déjà répondre à votre question", live_suggestions: "En décrivant votre problème, nous afficherons les guides pertinents.", what_next: "Et ensuite ?", confirmation_email: "Vous recevrez un e-mail de confirmation avec un numéro de ticket.", business_hours: "Une personne le lira pendant les heures ouvrées.", replies_here: "Les réponses apparaîtront dans vos demandes.",
    loading_request: "Chargement de la demande…", sign_in_view_request: "Connectez-vous pour voir cette demande", request_customer_only: "Cette demande est réservée à son client.", back_to_requests: "Retour aux demandes", older_messages_error: "Impossible de charger les anciens messages", reply_sent: "Réponse envoyée", team_notified: "L’équipe a été prévenue.", attach_error: "Impossible de joindre le fichier", upload_again: "Réessayez l’envoi.", resolved_reopen: "Cette demande est résolue. Répondre la rouvrira — inutile d’en créer une nouvelle.", load_older: "Charger les anciens messages", you: "Vous", reply_reopen: "Répondre pour rouvrir cette demande…", add_request: "Ajouter à cette demande…", your_reply: "Votre réponse", attach_file: "Joindre un fichier", reply_reopen_button: "Répondre et rouvrir", send_reply: "Envoyer la réponse", reply_error: "Impossible d’envoyer la réponse. Réessayez ; votre texte est conservé.", signed_in_as: "Vous êtes connecté en tant que", manage_notifications: "Gérer les notifications",
    sign_in_profile: "Connectez-vous pour voir votre profil", profile_after_signin: "Votre profil est disponible après connexion par e-mail.", your_profile: "Votre profil", profile_description: "Comment nous vous contactons et ce que nous envoyons.", details: "Détails", photo: "Photo", profile_photos_managed: "Les photos de profil sont gérées par votre équipe d’assistance.", name: "Nom", email_description: "Utilisé pour la connexion et les réponses. Le changement nécessite une vérification.", verified: "Vérifié", company: "Entreprise", save_profile: "Enregistrer le profil", profile_save_error: "Impossible d’enregistrer votre profil. Réessayez.", notifications: "Notifications", replies_requests: "Réponses à mes demandes", status_changes: "Changements de statut de mes demandes", feedback_updates: "Mises à jour des retours suivis", product_changelog: "Nouveautés produit", satisfaction_surveys: "Questionnaires de satisfaction", language_time: "Langue et heure", language: "Langue", time_zone: "Fuseau horaire", your_data: "Vos données", download_data: "Télécharger vos données", download_export: "Télécharger l’export", delete_account: "Supprimer le compte", delete_anonymise: "Supprimer et anonymiser votre compte",
  },
  es: {
    loading_article: "Cargando artículo…", article_not_found: "Artículo no encontrado", article_unpublished: "Puede haberse movido o dejado de publicar.", updated_date: "Actualizado el {date}", article_feedback_thanks: "Gracias — tu comentario llegará a quien mantiene esta página.", was_helpful: "¿Te resultó útil?", yes: "Sí", no: "No", helpful_count: "A {count} personas les resultó útil", anything_add: "¿Algo que debamos añadir? (opcional)", what_looking: "¿Qué estabas buscando?", article_feedback: "Comentario sobre el artículo", send_feedback: "Enviar comentario", feedback_error: "No se pudo registrar el comentario. Inténtalo de nuevo.", back_to_guides: "Volver a las guías", article_not_answer: "Esto no respondió a mi pregunta",
    changelog: "Novedades", changelog_description: "Lo que hemos publicado, empezando por lo más reciente.", subscription_settings: "Ajustes de suscripción", loading_updates: "Cargando novedades…", changelog_unavailable: "Novedades no disponibles", no_updates: "Aún no hay novedades publicadas", check_updates: "Vuelve aquí para ver las actualizaciones del producto.", updates_loaded: "{count} actualización{suffix} cargada{suffix}",
    loading_feedback: "Cargando comentarios…", feedback_unavailable: "Comentarios no disponibles", no_feedback_board: "Aún no hay un tablero de comentarios", no_feedback_board_description: "No hay un tablero público configurado para este portal.", feedback_description: "Vota por lo que te importa. Los suscriptores reciben novedades cuando algo cambia.", suggest_something: "Sugerir algo", suggest_description: "Describe el problema para que el equipo pueda entenderlo.", cancel: "Cancelar", submit: "Enviar", title: "Título", what_trying: "¿Qué intentas hacer?", submit_feedback_error: "No se pudo enviar la sugerencia. Inténtalo de nuevo.", view: "Vista", top_voted: "Más votadas", roadmap: "Hoja de ruta", search_feedback: "Buscar comentarios", loading_ideas: "Cargando ideas…", ideas_unavailable: "No se pudieron cargar las ideas", no_ideas_match: "No hay ideas que coincidan", suggest_first: "Prueba otra búsqueda o sugiere la primera idea.", nothing_here: "Aún no hay nada", ideas_loaded: "{count} idea{suffix} cargada{suffix}",
    loading_feedback_item: "Cargando comentario…", feedback_item_unavailable: "Comentario no disponible", feedback_item_private: "Puede haberse eliminado o no ser público.", back_to_feedback: "Volver a comentarios", submitted_date: "Enviado el {date}", discussion: "Debate", loading_comments: "Cargando comentarios…", comments_error: "No se pudieron cargar los comentarios. Inténtalo de nuevo.", no_comments: "Aún no hay comentarios.", customer: "Cliente", comments_loaded: "{count} comentario{suffix} cargado{suffix}", add_discussion: "Añadir al debate…", sign_in_comment: "Inicia sesión para comentar esta solicitud.", post_comment_error: "No se pudo publicar el comentario. Inténtalo de nuevo.", post_comment: "Publicar comentario", sign_in_comment_link: "Iniciar sesión para comentar",
    loading_forms: "Cargando formularios…", forms_unavailable: "Formularios no disponibles", forms: "Formularios", contact_forms: "Formularios de contacto", choose_form: "Elige el formulario que mejor se ajuste a lo que necesitas.", no_forms: "No hay formularios disponibles", no_forms_description: "Aún no hay formularios publicados aquí.", sign_in_required: "Inicio de sesión requerido", loading_form: "Cargando formulario…", sign_in_use_form: "Inicia sesión para usar este formulario", form_authenticated: "Este formulario está disponible para clientes con sesión iniciada.", form_unavailable: "Formulario no disponible", form_not_found: "Formulario no encontrado", form_unpublished: "Puede haberse dejado de publicar.", back_to_forms: "Volver a formularios", response_received: "Respuesta recibida",
    loading_survey: "Cargando encuesta…", survey_unavailable: "Encuesta no disponible", survey_expired: "La encuesta puede haber caducado o sido eliminada.", survey_thanks: "Gracias por tus comentarios. Tu respuesta se ha registrado.", thank_you: "Gracias", survey_intro: "Una breve pregunta sobre tu experiencia de soporte.", choose_one: "Elige una…", survey_submit_error: "No se pudo registrar tu respuesta. Inténtalo de nuevo.", submit_response: "Enviar respuesta",
    sign_in_before_request: "Inicia sesión antes de enviar una solicitud", session_request_history: "La sesión del portal conecta tu historial y respuestas contigo.", thanks_on_it: "Gracias — nos ocuparemos de ello", request_created: "Tu solicitud es", view_request: "Ver solicitud", back_help_centre: "Volver al centro de ayuda", specific_help: "Cuanto más específica sea tu solicitud, antes podremos ayudarte.", help_subject: "¿Con qué necesitas ayuda?", tell_more: "Cuéntanos más", urgency: "¿Qué urgencia tiene?", blocking: "Bloqueante", major: "Importante", minor: "Menor", question: "Solo una pregunta", your_email: "Tu correo", attachments: "Archivos adjuntos", choose_attachments: "Elegir capturas o registros", browse_guides_instead: "Ver las guías", request_error: "No se pudo enviar la solicitud. Tu borrador sigue aquí.", suggested_guides: "Estas guías quizá ya respondan a tu pregunta", what_next: "Qué ocurre después",
    loading_request: "Cargando solicitud…", sign_in_view_request: "Inicia sesión para ver esta solicitud", request_customer_only: "Esta solicitud solo está disponible para su cliente.", back_to_requests: "Volver a solicitudes", older_messages_error: "No se pudieron cargar mensajes anteriores", reply_sent: "Respuesta enviada", team_notified: "El equipo ha sido avisado.", attach_error: "No se pudo adjuntar el archivo", upload_again: "Intenta subirlo de nuevo.", resolved_reopen: "Esta solicitud está resuelta. Responderla la reabrirá — no necesitas crear otra.", load_older: "Cargar mensajes anteriores", you: "Tú", your_reply: "Tu respuesta", attach_file: "Adjuntar archivo", reply_reopen_button: "Responder y reabrir", send_reply: "Enviar respuesta", reply_error: "No se pudo enviar la respuesta. Inténtalo de nuevo; tu texto sigue aquí.", signed_in_as: "Has iniciado sesión como", manage_notifications: "Gestionar notificaciones",
    sign_in_profile: "Inicia sesión para ver tu perfil", profile_after_signin: "Tu perfil estará disponible después de iniciar sesión por correo.", your_profile: "Tu perfil", profile_description: "Cómo contactamos contigo y qué enviamos.", details: "Detalles", photo: "Foto", name: "Nombre", verified: "Verificado", company: "Empresa", save_profile: "Guardar perfil", notifications: "Notificaciones", language_time: "Idioma y hora", language: "Idioma", time_zone: "Zona horaria", your_data: "Tus datos", download_data: "Descargar tus datos", download_export: "Descargar exportación", delete_account: "Eliminar cuenta", delete_anonymise: "Eliminar y anonimizar tu cuenta",
  },
  ar: {
    loading_article: "جار تحميل المقال…", article_not_found: "المقال غير موجود", article_unpublished: "ربما تم نقله أو إلغاء نشره.", updated_date: "تم التحديث في {date}", article_feedback_thanks: "شكرًا — تم إرسال ملاحظتك إلى مسؤول هذه الصفحة.", was_helpful: "هل كان هذا مفيدًا؟", yes: "نعم", no: "لا", helpful_count: "وجد {count} أشخاص هذا مفيدًا", anything_add: "هل هناك ما ينبغي إضافته؟ (اختياري)", what_looking: "ما الذي كنت تبحث عنه؟", send_feedback: "إرسال الملاحظات", feedback_error: "تعذر تسجيل الملاحظات. حاول مرة أخرى.", back_to_guides: "العودة إلى الأدلة", article_not_answer: "لم يجب هذا عن سؤالي",
    changelog: "سجل التحديثات", changelog_description: "ما أطلقناه، من الأحدث إلى الأقدم.", subscription_settings: "إعدادات الاشتراك", loading_updates: "جار تحميل التحديثات…", changelog_unavailable: "سجل التحديثات غير متاح", no_updates: "لا توجد تحديثات منشورة بعد", check_updates: "عد إلى هنا لمعرفة تحديثات المنتج.", updates_loaded: "تم تحميل {count} تحديث",
    loading_feedback: "جار تحميل الملاحظات…", feedback_unavailable: "الملاحظات غير متاحة", no_feedback_board: "لا توجد لوحة ملاحظات بعد", no_feedback_board_description: "لم يتم إعداد لوحة ملاحظات عامة لهذه البوابة.", feedback_description: "صوّت لما يهمك. سيتلقى المشتركون تحديثات عند تغيّر الحالة.", suggest_something: "اقترح شيئًا", suggest_description: "صِف المشكلة التي تواجهها ليساعد الفريق على فهمها.", cancel: "إلغاء", submit: "إرسال", title: "العنوان", what_trying: "ماذا تحاول أن تفعل؟", submit_feedback_error: "تعذر إرسال الاقتراح. حاول مرة أخرى.", view: "العرض", top_voted: "الأعلى تصويتًا", roadmap: "خارطة الطريق", search_feedback: "البحث في الملاحظات", loading_ideas: "جار تحميل الأفكار…", ideas_unavailable: "تعذر تحميل الأفكار", no_ideas_match: "لا توجد أفكار مطابقة", suggest_first: "جرّب بحثًا آخر أو اقترح الفكرة الأولى.", nothing_here: "لا شيء هنا بعد", ideas_loaded: "تم تحميل {count} فكرة",
    loading_feedback_item: "جار تحميل الملاحظة…", feedback_item_unavailable: "الملاحظة غير متاحة", feedback_item_private: "ربما تمت إزالتها أو ليست عامة.", back_to_feedback: "العودة إلى الملاحظات", submitted_date: "أُرسلت في {date}", discussion: "النقاش", loading_comments: "جار تحميل التعليقات…", comments_error: "تعذر تحميل التعليقات. حاول مرة أخرى.", no_comments: "لا توجد تعليقات بعد.", customer: "العميل", comments_loaded: "تم تحميل {count} تعليق", add_discussion: "أضف إلى النقاش…", sign_in_comment: "سجّل الدخول للتعليق على هذا الطلب.", post_comment_error: "تعذر نشر التعليق. حاول مرة أخرى.", post_comment: "نشر التعليق", sign_in_comment_link: "سجّل الدخول للتعليق",
    loading_forms: "جار تحميل النماذج…", forms_unavailable: "النماذج غير متاحة", forms: "النماذج", contact_forms: "نماذج التواصل", choose_form: "اختر النموذج الأنسب لما تحتاجه.", no_forms: "لا توجد نماذج متاحة", no_forms_description: "لا توجد نماذج منشورة هنا بعد.", sign_in_required: "تسجيل الدخول مطلوب", loading_form: "جار تحميل النموذج…", sign_in_use_form: "سجّل الدخول لاستخدام هذا النموذج", form_authenticated: "هذا النموذج متاح للعملاء المسجلين.", form_unavailable: "النموذج غير متاح", form_not_found: "النموذج غير موجود", form_unpublished: "ربما تم إلغاء نشر هذا النموذج.", back_to_forms: "العودة إلى النماذج", response_received: "تم استلام الرد",
    loading_survey: "جار تحميل الاستبيان…", survey_unavailable: "الاستبيان غير متاح", survey_expired: "ربما انتهت صلاحية الاستبيان أو تمت إزالته.", survey_thanks: "شكرًا لملاحظاتك. تم تسجيل ردك.", thank_you: "شكرًا لك", survey_intro: "سؤال قصير عن تجربتك مع الدعم.", choose_one: "اختر…", survey_submit_error: "تعذر تسجيل ردك. حاول مرة أخرى.", submit_response: "إرسال الرد",
    sign_in_before_request: "سجّل الدخول قبل إرسال الطلب", session_request_history: "تربط جلسة البوابة سجل طلباتك وردودك بحسابك.", thanks_on_it: "شكرًا — سنهتم بالأمر", request_created: "طلبك هو", view_request: "عرض الطلب", back_help_centre: "العودة إلى مركز المساعدة", specific_help: "كلما كان طلبك أكثر تحديدًا، استطعنا مساعدتك أسرع.", help_subject: "بماذا تحتاج المساعدة؟", tell_more: "أخبرنا بالمزيد", urgency: "ما مدى الاستعجال؟", blocking: "حاجب", major: "كبير", minor: "بسيط", question: "مجرد سؤال", your_email: "بريدك الإلكتروني", attachments: "المرفقات", choose_attachments: "اختر لقطات أو سجلات", browse_guides_instead: "تصفح الأدلة", request_error: "تعذر إرسال الطلب. ما زالت مسودتك محفوظة.", suggested_guides: "قد تجيب هذه الأدلة عن سؤالك", what_next: "ماذا سيحدث بعد ذلك؟",
    loading_request: "جار تحميل الطلب…", sign_in_view_request: "سجّل الدخول لعرض هذا الطلب", request_customer_only: "هذا الطلب متاح لعميله فقط.", back_to_requests: "العودة إلى الطلبات", older_messages_error: "تعذر تحميل الرسائل القديمة", reply_sent: "تم إرسال الرد", team_notified: "تم إخطار الفريق.", attach_error: "تعذر إرفاق الملف", upload_again: "حاول رفعه مرة أخرى.", resolved_reopen: "تم حل هذا الطلب. سيؤدي الرد إلى إعادة فتحه — لا حاجة لإنشاء طلب جديد.", load_older: "تحميل الرسائل القديمة", you: "أنت", your_reply: "ردك", attach_file: "إرفاق ملف", reply_reopen_button: "الرد وإعادة الفتح", send_reply: "إرسال الرد", reply_error: "تعذر إرسال الرد. حاول مرة أخرى؛ ما زال نصك محفوظًا.", signed_in_as: "تم تسجيل الدخول باسم", manage_notifications: "إدارة الإشعارات",
    sign_in_profile: "سجّل الدخول لعرض ملفك الشخصي", profile_after_signin: "يتوفر ملفك الشخصي بعد تسجيل الدخول بالبريد الإلكتروني.", your_profile: "ملفك الشخصي", profile_description: "كيفية التواصل معك وما نرسله.", details: "التفاصيل", photo: "الصورة", name: "الاسم", verified: "تم التحقق", company: "الشركة", save_profile: "حفظ الملف الشخصي", notifications: "الإشعارات", language_time: "اللغة والوقت", language: "اللغة", time_zone: "المنطقة الزمنية", your_data: "بياناتك", download_data: "تنزيل بياناتك", download_export: "تنزيل التصدير", delete_account: "حذف الحساب", delete_anonymise: "حذف وإخفاء هوية الحساب",
  },
};

function localeFor(value: string | undefined): string {
  const base = (value || "en").trim().toLowerCase().replaceAll("_", "-").split("-", 1)[0] ?? "en";
  return messages[base] ? base : "en";
}

export function portalText(data: PortalBootstrap | undefined, key: string, fallback: string, values?: Record<string, string | number>) {
  const language = localeFor(data?.viewer?.language || data?.portal.default_language);
  let value = supplementalMessages[language]?.[key] ?? messages[language]?.[key] ?? messages.en?.[key] ?? fallback;
  for (const [name, replacement] of Object.entries(values ?? {})) value = value.replaceAll(`{${name}}`, String(replacement));
  return value;
}
