// Code generated by scripts/generate-ts-api.mjs from embedded/openapi.json. Do not edit.
// Regenerate with: node scripts/generate-openapi.mjs && node scripts/generate-ts-api.mjs

export type ApiAnalyticsRollup = {
  "metric": string;
  "grain": string;
  "bucket": ApiTimestamp;
  "dimensions": {
  [key: string]: unknown;
};
  "value": number;
  "count": number;
  "computed_at": ApiTimestamp;
};

export type ApiAnalyticsRollupPage = ApiPageOf & {
  "data"?: ApiAnalyticsRollup[];
};

export type ApiAnalyticsSearchTerm = {
  "query": string;
  "count": number;
  "last_occurred_at": ApiTimestamp;
};

export type ApiAnalyticsSearchTermPage = ApiPageOf & {
  "data"?: ApiAnalyticsSearchTerm[];
};

export type ApiAttachment = {
  "id": ApiId;
  "name": string;
  "mime_type": string;
  "size_bytes": number;
  "url": string;
  "thumbnail_url": string | null;
};

export type ApiAttributeDefinition = {
  "id": ApiId;
  "workspace_id": ApiId;
  "entity_type": string;
  "key": string;
  "label": string;
  "type": string;
  "description": string | null;
  "options": string[];
  "allowed_sources": string[];
  "required_capability": string | null;
  "sensitive": boolean;
  "searchable": boolean;
  "validation": ApiFieldValidation | null;
  "retention_days": number | null;
  "created_at": ApiTimestamp;
};

export type ApiAttributeDefinitionPage = ApiPageOf & {
  "data"?: ApiAttributeDefinition[];
};

export type ApiBulkConversationUpdateRequest = {
  "ids": ApiId[];
  "action": "assign" | "state";
  "assignee_id"?: ApiId | null;
  "state"?: string;
};

export type ApiBulkConversationUpdateResult = {
  "data": {
  "id": ApiId;
  "state": string;
  "assignee_id": string | null;
}[];
  "count": number;
};

export type ApiConversation = {
  "id": ApiId;
  "workspace_id": ApiId;
  "inbox_id": ApiId;
  "channel": string;
  "subject": string | null;
  "state": string;
  "priority": string;
  "customer_id": string | null;
  "visitor_id": string | null;
  "assignee_id": string | null;
  "team_id": string | null;
  "tag_ids": ApiId[];
  "ticket_id": string | null;
  "unread": boolean;
  "message_count": number;
  "last_message_preview": string;
  "last_message_at": ApiTimestamp;
  "last_customer_at": string | null;
  "snoozed_until": string | null;
  "sla": ApiConversationSLA | null;
  "viewers": ApiId[];
  "created_at": ApiTimestamp;
};

export type ApiConversationCounts = {
  "all": number;
  "unassigned": number;
  "mine": number;
  "following": number;
  "mentioned": number;
  "waiting_on_us": number;
  "waiting_on_customer": number;
  "snoozed": number;
  "resolved": number;
  "spam": number;
  "sla_approaching": number;
  "sla_breached": number;
};

export type ApiConversationLink = {
  "id": ApiId;
  "workspace_id": ApiId;
  "source_id": ApiId;
  "target_id": ApiId;
  "relation": "related" | "duplicate_of" | "follow_up";
  "created_by"?: string | null;
  "created_at": ApiTimestamp;
};

export type ApiConversationLinkInput = {
  "target_id": ApiId;
  "relation"?: "related" | "duplicate_of" | "follow_up";
};

export type ApiConversationLinkPage = ApiPageOf & {
  "data"?: ApiConversationLink[];
};

export type ApiConversationPage = ApiPageOf & {
  "data"?: ApiConversation[];
};

export type ApiConversationSLA = {
  "policy_id": ApiId;
  "state": string;
  "first_response_remaining": number | null;
  "next_response_remaining": number | null;
  "resolution_remaining": number | null;
  "paused_reason": string | null;
};

export type ApiCreateConversationMessageRequest = {
  "kind"?: "reply" | "note";
  "author_name"?: string;
  "body": string;
  "file_ids"?: ApiId[];
  "mentioned_member_ids"?: ApiId[];
};

export type ApiCreateConversationRequest = {
  "inbox_id": ApiId;
  "channel": string;
  "subject"?: string | null;
  "customer_id"?: string | null;
  "author_name"?: string;
  "body": string;
  "file_ids"?: ApiId[];
};

export type ApiCreateTicketRequest = {
  "title": string;
  "description"?: string;
  "type"?: string | null;
  "priority"?: string;
  "customer_id"?: string | null;
  "company_id"?: string | null;
  "inbox_id": ApiId;
  "channel"?: string;
  "assignee_id"?: string | null;
  "team_id"?: string | null;
  "conversation_id"?: string | null;
  "parent_id"?: string | null;
  "due_at"?: string | null;
  "field_values"?: {
  [key: string]: unknown;
};
};

export type ApiCustomer = {
  "id": ApiId;
  "workspace_id": ApiId;
  "name": string | null;
  "email": string | null;
  "phone": string | null;
  "avatar_url": string | null;
  "external_id": string | null;
  "verification": string;
  "company_ids": ApiId[];
  "language": string | null;
  "timezone": string | null;
  "attributes": {
  [key: string]: unknown;
};
  "masked_attribute_keys": string[];
  "tag_ids": ApiId[];
  "owner_id": string | null;
  "presence": string;
  "current_url": string | null;
  "first_seen_at": ApiTimestamp;
  "last_seen_at": string | null;
  "last_contacted_at": string | null;
  "version": number;
};

export type ApiCustomer360 = {
  "companies": ApiCustomer360Company[];
  "companies_truncated": boolean;
  "conversations": ApiCustomer360Conversation[];
  "conversations_truncated": boolean;
  "tickets": ApiCustomer360Ticket[];
  "tickets_truncated": boolean;
  "events": ApiCustomer360Event[];
  "events_truncated": boolean;
  "page_journey": ApiCustomer360PageVisit[];
  "page_journey_truncated": boolean;
  "current_page"?: ApiCustomer360PageVisit | null;
  "device"?: ApiCustomer360Device | null;
  "sessions": ApiCustomer360Session[];
  "sessions_truncated": boolean;
  "feedback": ApiCustomer360Feedback[];
  "feedback_truncated": boolean;
  "surveys": ApiCustomer360Survey[];
  "surveys_truncated": boolean;
  "articles": ApiCustomer360Article[];
  "articles_truncated": boolean;
  "identities": ApiCustomer360Identity[];
  "identities_truncated": boolean;
  "merges": ApiCustomer360Merge[];
  "merges_truncated": boolean;
  "context_metadata"?: {
  [key: string]: unknown;
};
};

export type ApiCustomer360Article = {
  "id": ApiId;
  "article_id": ApiId;
  "title": string;
  "slug": string;
  "helpful": boolean;
  "comment"?: string;
  "created_at": ApiTimestamp;
};

export type ApiCustomer360Company = {
  "id": ApiId;
  "name": string;
  "domain"?: string | null;
  "tier"?: string | null;
};

export type ApiCustomer360Conversation = {
  "id": ApiId;
  "subject"?: string | null;
  "state": string;
  "channel": string;
  "inbox_id": ApiId;
  "last_message_preview": string;
  "last_message_at"?: string | null;
  "created_at": ApiTimestamp;
};

export type ApiCustomer360Device = {
  "device"?: string;
  "browser"?: string;
  "os"?: string;
  "language"?: string;
  "timezone"?: string;
  "platform"?: string;
  "referrer_origin"?: string;
  "user_agent"?: string;
  "viewport"?: {
  "width"?: number;
  "height"?: number;
  "device_pixel_ratio"?: number;
};
};

export type ApiCustomer360Event = {
  "id": ApiId;
  "type": string;
  "source": string;
  "url"?: string | null;
  "request_id"?: string | null;
  "occurred_at": ApiTimestamp;
};

export type ApiCustomer360Feedback = {
  "id": ApiId;
  "title": string;
  "board_id": ApiId;
  "board_name": string;
  "status": string;
  "vote_count": number;
  "comment_count": number;
  "created_at": ApiTimestamp;
};

export type ApiCustomer360Identity = {
  "id": ApiId;
  "kind": "email" | "phone";
  "value": string;
  "verified_at"?: string | null;
  "is_primary": boolean;
  "created_at": ApiTimestamp;
};

export type ApiCustomer360Merge = {
  "id": ApiId;
  "winner_id": ApiId;
  "loser_id": ApiId;
  "moved_counts": {
  [key: string]: unknown;
};
  "reversible_until"?: string | null;
  "reversed_at"?: string | null;
  "created_at": ApiTimestamp;
};

export type ApiCustomer360PageVisit = {
  "id": ApiId;
  "url"?: string | null;
  "title"?: string;
  "device"?: string;
  "browser"?: string;
  "os"?: string;
  "platform"?: string;
  "referrer_origin"?: string;
  "user_agent"?: string;
  "viewport"?: {
  "width"?: number;
  "height"?: number;
  "device_pixel_ratio"?: number;
};
  "occurred_at": ApiTimestamp;
};

export type ApiCustomer360Session = {
  "id": ApiId;
  "device"?: string | null;
  "browser"?: string | null;
  "os"?: string | null;
  "referrer"?: string | null;
  "landing_url"?: string | null;
  "current_url"?: string | null;
  "current_title"?: string | null;
  "language"?: string | null;
  "timezone"?: string | null;
  "platform"?: string | null;
  "user_agent"?: string | null;
  "viewport"?: {
  "width"?: number;
  "height"?: number;
  "device_pixel_ratio"?: number;
} | null;
  "page_views": number;
  "started_at": ApiTimestamp;
  "last_seen_at": ApiTimestamp;
  "ended_at"?: string | null;
};

export type ApiCustomer360Survey = {
  "id": ApiId;
  "survey_id": ApiId;
  "survey_name": string;
  "survey_type": string;
  "score"?: number | null;
  "comment"?: string;
  "submitted_at"?: string | null;
};

export type ApiCustomer360Ticket = {
  "id": ApiId;
  "number": number;
  "prefix": string;
  "title": string;
  "status": string;
  "priority": string;
  "conversation_id"?: string | null;
  "updated_at": ApiTimestamp;
  "created_at": ApiTimestamp;
};

export type ApiCustomerPage = ApiPageOf & {
  "data"?: ApiCustomer[];
};

export type ApiError = {
  "error": ApiErrorBody;
};

export type ApiErrorBody = {
  "code": string;
  "message": string;
  "request_id": ApiId;
  "details"?: {
  [key: string]: unknown;
};
};

export type ApiEventEnvelope = {
  "id": ApiId;
  "type": string;
  "workspace_id": ApiId;
  "occurred_at": ApiTimestamp;
  "sequence": number;
  "data": {
  [key: string]: unknown;
};
};

export type ApiFieldDefinition = {
  "id": ApiId;
  "workspace_id": ApiId;
  "key": string;
  "label": string;
  "type": string;
  "description": string | null;
  "options": string[] | null;
  "required": boolean;
  "visibility": string;
  "sensitive": boolean;
  "searchable": boolean;
  "allowed_sources": string[];
  "required_capability": string | null;
  "validation": ApiFieldValidation | null;
  "created_at": ApiTimestamp;
};

export type ApiFieldDefinitionPage = ApiPageOf & {
  "data"?: ApiFieldDefinition[];
};

export type ApiFieldValidation = {
  "min"?: number;
  "max"?: number;
  "min_length"?: number;
  "max_length"?: number;
  "pattern"?: string;
};

export type ApiId = string;

export type ApiLegalHold = {
  "id": ApiId;
  "workspace_id": ApiId;
  "category": "all" | "events" | "sessions" | "webhooks" | "surveys" | "audit";
  "reason": string;
  "created_by"?: ApiId | null;
  "released_by"?: ApiId | null;
  "created_at": ApiTimestamp;
  "released_at"?: string | null;
};

export type ApiLegalHoldInput = {
  "category": "all" | "events" | "sessions" | "webhooks" | "surveys" | "audit";
  "reason": string;
};

export type ApiLegalHoldPage = ApiPageOf & {
  "data"?: ApiLegalHold[];
};

export type ApiMacro = {
  "id": ApiId;
  "workspace_id": ApiId;
  "name": string;
  "folder": string;
  "scope": "personal" | "team" | "workspace";
  "owner_id": string | null;
  "team_id": string | null;
  "body": string;
  "actions": ApiMacroAction[];
  "usage_count": number;
  "created_at": ApiTimestamp;
  "updated_at": ApiTimestamp;
};

export type ApiMacroAction = {
  "id": string;
  "type": string;
  "params": {
  [key: string]: unknown;
};
};

export type ApiMacroExecution = {
  "macro_id": ApiId;
  "subject_type": string;
  "subject_id": ApiId;
  "actions_applied": ApiMacroAction[];
};

export type ApiMacroExecutionRequest = {
  "subject_type": "conversation" | "ticket";
  "subject_id": ApiId;
};

export type ApiMacroInput = {
  "name": string;
  "folder"?: string;
  "scope"?: "personal" | "team" | "workspace";
  "owner_id"?: ApiId;
  "team_id"?: ApiId;
  "body"?: string;
  "actions"?: ApiMacroAction[];
};

export type ApiMacroPage = ApiPageOf & {
  "data"?: ApiMacro[];
};

export type ApiMessage = {
  "id": ApiId;
  "client_id": string | null;
  "conversation_id": ApiId;
  "workspace_id": ApiId;
  "kind": string;
  "author_type": string;
  "author_id": string | null;
  "author_name": string;
  "author_avatar_url": string | null;
  "body": string;
  "event_type": string | null;
  "event_data": {
  [key: string]: unknown;
} | null;
  "attachments": ApiAttachment | string[];
  "quoted_message_id": string | null;
  "delivery": string;
  "edited_at": string | null;
  "redacted_at": string | null;
  "sequence": number;
  "created_at": ApiTimestamp;
};

export type ApiMessagePage = ApiPageOf & {
  "data"?: ApiMessage[];
};

export type ApiOpsCheck = {
  "id": string;
  "status": "pass" | "warn" | "fail";
  "detail": string;
};

export type ApiOpsSummary = {
  "jobs": {
  [key: string]: unknown;
};
  "webhooks": {
  [key: string]: unknown;
};
  "email": {
  [key: string]: unknown;
};
  "storage": {
  [key: string]: unknown;
};
  "realtime": {
  [key: string]: unknown;
};
  "checks": ApiOpsCheck[];
  "computed_at": ApiTimestamp;
};

export type ApiPage = {
  "data": unknown[];
  "has_more": boolean;
  "next_cursor": string | null;
};

export type ApiPageOf = {
  "data": unknown[];
  "has_more": boolean;
  "next_cursor": string | null;
};

export type ApiPortalMessage = {
  "id": ApiId;
  "conversation_id": ApiId;
  "kind": string;
  "author_type": string;
  "author_id": string | null;
  "author_name": string;
  "body": string;
  "delivery": string;
  "sequence": number;
  "edited_at": string | null;
  "created_at": ApiTimestamp;
  "attachments": ApiAttachment[];
};

export type ApiPortalTicket = {
  "id": ApiId;
  "number": number;
  "prefix": string;
  "title": string;
  "description": string;
  "status": string;
  "priority": string;
  "conversation_id": string | null;
  "created_at": ApiTimestamp;
  "updated_at": ApiTimestamp;
};

export type ApiPortalTicketDetail = {
  "ticket": ApiPortalTicket;
  "messages": ApiPortalMessage[];
  "has_more": boolean;
  "next_cursor": string | null;
};

export type ApiPortalTicketPage = ApiPageOf & {
  "data"?: ApiPortalTicket[];
};

export type ApiSavedReply = {
  "id": ApiId;
  "workspace_id": ApiId;
  "name": string;
  "shortcut": string | null;
  "folder": string | null;
  "scope": string;
  "body": string;
  "usage_count": number;
  "created_at": ApiTimestamp;
  "updated_at": ApiTimestamp;
};

export type ApiSavedReplyInput = {
  "name": string;
  "shortcut"?: string;
  "folder"?: string;
  "scope"?: string;
  "owner_id"?: ApiId;
  "team_id"?: ApiId;
  "body": string;
};

export type ApiSavedReplyPage = ApiPageOf & {
  "data"?: ApiSavedReply[];
};

export type ApiSearchPage = ApiPageOf & {
  "data"?: ApiSearchResult[];
};

export type ApiSearchResult = {
  "kind": string;
  "title": string;
  "snippet": string;
  "entity_id": ApiId;
  "conversation_id": string | null;
};

export type ApiTask = {
  "id": ApiId;
  "workspace_id": ApiId;
  "title": string;
  "description": string;
  "state": "open" | "completed" | "cancelled";
  "subject_type": string;
  "subject_id": string;
  "assignee_id": string;
  "assignee_name"?: string;
  "due_at": string | null;
  "created_by": string;
  "created_by_name"?: string;
  "completed_at": string | null;
  "created_at": ApiTimestamp;
  "updated_at": ApiTimestamp;
};

export type ApiTaskInput = {
  "title": string;
  "description"?: string;
  "subject_type"?: "conversation" | "ticket" | "customer" | "feedback";
  "subject_id"?: ApiId;
  "assignee_id"?: ApiId;
  "due_at"?: string | null;
};

export type ApiTaskPage = ApiPageOf & {
  "data"?: ApiTask[];
};

export type ApiTestEmailResult = {
  "job_id": ApiId;
  "recipient": string;
  "status": "queued";
};

export type ApiTicket = {
  "id": ApiId;
  "workspace_id": ApiId;
  "number": number;
  "prefix": string;
  "title": string;
  "description": string;
  "status": string;
  "priority": string;
  "type": string | null;
  "customer_id": string | null;
  "company_id": string | null;
  "inbox_id": ApiId;
  "channel": string;
  "assignee_id": string | null;
  "team_id": string | null;
  "conversation_id": string | null;
  "parent_id": string | null;
  "child_ids": ApiId[];
  "linked_ticket_ids": ApiId[];
  "tag_ids": ApiId[];
  "field_values": {
  [key: string]: unknown;
};
  "sla": ApiConversationSLA | null;
  "viewers": ApiId[];
  "due_at": string | null;
  "version": number;
  "created_at": ApiTimestamp;
  "updated_at": ApiTimestamp;
  "resolved_at": string | null;
  "closed_at": string | null;
};

export type ApiTicketPage = ApiPageOf & {
  "data"?: ApiTicket[];
};

export type ApiTimestamp = string;

export type ApiUpdateConversationRequest = {
  "subject"?: string | null;
  "state"?: string;
  "priority"?: string;
};

export type ApiUpdateCustomerRequest = {
  "version": number;
  "name"?: string | null;
  "email"?: string | null;
  "phone"?: string | null;
  "language"?: string | null;
  "timezone"?: string | null;
};

export type ApiUpdateTaskRequest = {
  "title"?: string;
  "description"?: string;
  "state"?: "open" | "completed" | "cancelled";
  "assignee_id"?: ApiId;
  "due_at"?: string | null;
};

export type ApiUpdateTicketRequest = {
  "title"?: string;
  "description"?: string;
  "type"?: string | null;
  "due_at"?: string | null;
  "expected_version": number;
};

export type ApiVisitorContext = {
  "visitor_id": ApiId;
  "customer_id"?: string | null;
  "presence": string;
  "first_seen_at": ApiTimestamp;
  "last_seen_at": ApiTimestamp;
  "current_page"?: ApiCustomer360PageVisit | null;
  "page_journey": ApiCustomer360PageVisit[];
  "page_journey_truncated": boolean;
  "device"?: ApiCustomer360Device | null;
  "session"?: ApiCustomer360Session | null;
  "context_metadata"?: {
  [key: string]: unknown;
};
};

export type ApiWidgetArticle = {
  "slug": string;
  "title": string;
  "excerpt": string;
  "body"?: string;
  "language": string;
  "helpful_count": number;
  "unhelpful_count": number;
};

export type ApiWidgetArticlePage = ApiPageOf & {
  "data"?: ApiWidgetArticle[];
};

export type ApiWorkspace = {
  "id": ApiId;
  "name": string;
  "slug": string;
  "default_language": string;
  "timezone": string;
  "ticket_prefix": string;
  "created_at": ApiTimestamp;
};

export type ApiOperationId =
  | "addPortalDomain"
  | "bulkUpdateConversations"
  | "confirmImport"
  | "convertConversationToTicket"
  | "createAPIKey"
  | "createArticle"
  | "createAutomationMacro"
  | "createAutomationReply"
  | "createAutomationRule"
  | "createChangelogEntry"
  | "createConversation"
  | "createConversationMessage"
  | "createEmailMailbox"
  | "createEvent"
  | "createExport"
  | "createFeedbackBoard"
  | "createFeedbackItem"
  | "createForm"
  | "createImport"
  | "createKnowledgeBase"
  | "createPublicFeedbackComment"
  | "createPublicFeedbackItem"
  | "createReport"
  | "createReportSchedule"
  | "createSavedView"
  | "createSLACalendar"
  | "createSLAPolicy"
  | "createSurvey"
  | "createTask"
  | "createTicket"
  | "createWebhook"
  | "createWorkspaceLegalHold"
  | "deleteApiKeysId"
  | "deleteAttributeDefinitionsId"
  | "deleteAuthSessionsId"
  | "deleteAuthTrustedDevicesId"
  | "deleteAutomationMacro"
  | "deleteCompaniesIdCustomersCustomerID"
  | "deleteCompaniesIdTagsTagID"
  | "deleteConversationsIdFollowersMe"
  | "deleteConversationsIdTagsTagID"
  | "deleteCustomersId"
  | "deleteCustomersIdTagsTagID"
  | "deleteEmailMailbox"
  | "deleteEmailTemplatesKey"
  | "deleteFieldDefinitionsId"
  | "deleteForm"
  | "deleteInboxesId"
  | "deleteInvitesId"
  | "deleteMembersId"
  | "deletePortalCustomerData"
  | "deletePortalDomain"
  | "deleteReport"
  | "deleteReportSchedule"
  | "deleteRolesId"
  | "deleteSavedView"
  | "deleteScimV20WorkspaceIDUsersId"
  | "deleteTagsId"
  | "deleteTeamsId"
  | "deleteTeamsIdMembersMemberId"
  | "deleteTicketsIdFollowersMe"
  | "deleteTicketsIdLinksTargetID"
  | "deleteTicketsIdTagsTagID"
  | "deleteWebhooksId"
  | "deleteWidgetFeedbackItemsIdSubscription"
  | "deleteWidgetsId"
  | "deleteWidgetsIdDomainsDomainID"
  | "downloadFile"
  | "exportAnalyticsCsv"
  | "exportAuditLogs"
  | "exportCompanies"
  | "exportCustomers"
  | "exportPortalCustomerData"
  | "exportSurveyResponses"
  | "getAnalyticsSummary"
  | "getAnalyticsWorkload"
  | "getArticle"
  | "getAttributeDefinitions"
  | "getAuthMe"
  | "getAuthOauthProviderCallback"
  | "getAuthOauthProviders"
  | "getAuthOauthProviderStart"
  | "getAuthSessions"
  | "getAuthTotp"
  | "getAuthTrustedDevices"
  | "getAutomationMacro"
  | "getAutomationRule"
  | "getBootstrap"
  | "getChangelogEntry"
  | "getCompanies"
  | "getCompaniesId"
  | "getCompaniesIdCustomers"
  | "getConversation"
  | "getConversationsCounts"
  | "getConversationsIdFollowers"
  | "getConversationsIdTranscript"
  | "getCustomer"
  | "getCustomer360"
  | "getCustomerCommandBindings"
  | "getCustomersIdExport"
  | "getCustomersIdSessions"
  | "getCustomersIdTimeline"
  | "getEmailStatus"
  | "getEmailTemplates"
  | "getExport"
  | "getExportManifest"
  | "getFeedbackBoardsId"
  | "getFeedbackItemsId"
  | "getFeedbackItemsIdComments"
  | "getFeedbackRoadmap"
  | "getFieldDefinitions"
  | "getForm"
  | "getImport"
  | "getInboxes"
  | "getInboxesId"
  | "getInvites"
  | "getInvitesLookupToken"
  | "getJobSummary"
  | "getKnowledgeBasesIdCollections"
  | "getMembers"
  | "getMeta"
  | "getNotifications"
  | "getNotificationsCount"
  | "getNotificationsPreferences"
  | "getOpenapiJson"
  | "getOperationalSummary"
  | "getPortalBootstrap"
  | "getPortalFilesId"
  | "getPortalForm"
  | "getPortalProfile"
  | "getPortals"
  | "getPortalsId"
  | "getPortalTickets"
  | "getPortalTicketsId"
  | "getPublicFeedbackItem"
  | "getPublicFeedbackWorkspaceIDBoards"
  | "getPublicForm"
  | "getPublicKnowledgeBasesWorkspaceIDArticlesSlug"
  | "getPublicSurveysWorkspaceIDId"
  | "getReport"
  | "getRoles"
  | "getSavedView"
  | "getScimV20WorkspaceIDUsers"
  | "getScimV20WorkspaceIDUsersId"
  | "getSearch"
  | "getSetupState"
  | "getSLACalendar"
  | "getSlaPoliciesId"
  | "getSurvey"
  | "getSurveysIdSummary"
  | "getTags"
  | "getTask"
  | "getTeams"
  | "getTicket"
  | "getTicketsDuplicates"
  | "getTicketsExport"
  | "getTicketsIdActivity"
  | "getTicketsIdChildren"
  | "getTicketsIdFollowers"
  | "getTicketsIdLinks"
  | "getVisitorsIdContext"
  | "getWebhooksId"
  | "getWebhooksIdDeliveries"
  | "getWidgetArticles"
  | "getWidgetArticlesSlug"
  | "getWidgetConfig"
  | "getWidgetConversationsIdCommands"
  | "getWidgetConversationsIdFilesFileID"
  | "getWidgetConversationsIdMessages"
  | "getWidgetFeedbackBoards"
  | "getWidgetFeedbackBoardsSlugItems"
  | "getWidgetForms"
  | "getWidgetFormsSlug"
  | "getWidgets"
  | "getWidgetsId"
  | "getWidgetsIdDomains"
  | "getWidgetsIdIdentitySecret"
  | "getWidgetsIdVersions"
  | "getWorkspaceSettings"
  | "getWorkspaceUsage"
  | "linkConversation"
  | "linkFeedbackSupportWork"
  | "listAllFeedbackItems"
  | "listAnalyticsNoResultSearches"
  | "listAnalyticsRollups"
  | "listAPIKeys"
  | "listArticleRevisions"
  | "listArticles"
  | "listAuditLogs"
  | "listAutomationExecutions"
  | "listAutomationMacros"
  | "listAutomationReplies"
  | "listAutomationRules"
  | "listChangelogEntries"
  | "listConversationLinks"
  | "listConversationMessages"
  | "listConversations"
  | "listCustomers"
  | "listEmailDeliveryEvents"
  | "listEmailMailboxes"
  | "listEmailSuppressions"
  | "listEvents"
  | "listExports"
  | "listFeedbackBoards"
  | "listFeedbackItems"
  | "listFeedbackLinks"
  | "listForms"
  | "listImports"
  | "listJobs"
  | "listKnowledgeBases"
  | "listMailboxEmailSuppressions"
  | "listMetricDefinitions"
  | "listPortalDomains"
  | "listPortalForms"
  | "listPublicChangelogEntries"
  | "listPublicFeedbackComments"
  | "listPublicFeedbackItems"
  | "listReports"
  | "listReportSchedules"
  | "listSavedViews"
  | "listSLACalendars"
  | "listSLAInstances"
  | "listSLAPolicies"
  | "listSurveyResponses"
  | "listSurveys"
  | "listTasks"
  | "listTickets"
  | "listWebhooks"
  | "listWorkspaceLegalHolds"
  | "mergeFeedbackItem"
  | "patchAttributeDefinitionsId"
  | "patchAuthProfile"
  | "patchCompaniesId"
  | "patchCompaniesIdAttributes"
  | "patchConversationsIdAssignee"
  | "patchConversationsIdInbox"
  | "patchConversationsIdMessagesMessageID"
  | "patchConversationsIdPriority"
  | "patchConversationsIdState"
  | "patchConversationsIdTeam"
  | "patchCustomerCommandBindingsId"
  | "patchCustomersIdAttributes"
  | "patchCustomersIdOwner"
  | "patchFeedbackItemsIdStatus"
  | "patchFieldDefinitionsId"
  | "patchInboxesId"
  | "patchMembersIdCapabilities"
  | "patchMembersIdRole"
  | "patchMembersMeAcceptingConversations"
  | "patchMembersMePresence"
  | "patchPortalsId"
  | "patchRolesId"
  | "patchScimV20WorkspaceIDUsersId"
  | "patchSlaPoliciesId"
  | "patchTeamsId"
  | "patchTicketsIdAssignee"
  | "patchTicketsIdCustomer"
  | "patchTicketsIdDue"
  | "patchTicketsIdInbox"
  | "patchTicketsIdParent"
  | "patchTicketsIdPriority"
  | "patchTicketsIdStatus"
  | "patchTicketsIdTeam"
  | "patchWebhooksId"
  | "patchWorkspaceBranding"
  | "patchWorkspaceGeneral"
  | "patchWorkspacePrivacy"
  | "patchWorkspaceSecurity"
  | "postApiKeysIdRotate"
  | "postArticlesIdPublish"
  | "postAttributeDefinitions"
  | "postAuthLogin"
  | "postAuthLogout"
  | "postAuthMagicLink"
  | "postAuthMagicLinkRedeem"
  | "postAuthPasswordChange"
  | "postAuthPasswordForgot"
  | "postAuthPasswordReset"
  | "postAuthSessionsRevokeOthers"
  | "postAuthSignup"
  | "postAuthTotpBegin"
  | "postAuthTotpChallenge"
  | "postAuthTotpComplete"
  | "postAuthTotpDisable"
  | "postAuthTrustedDevicesRevokeAll"
  | "postAuthVerifyEmail"
  | "postAuthVerifyEmailResend"
  | "postAutomationRepliesIdUse"
  | "postAutomationRulesIdDryRun"
  | "postBlockedContacts"
  | "postCompanies"
  | "postCompaniesIdTags"
  | "postConversationsIdCustomerCommands"
  | "postConversationsIdMerge"
  | "postConversationsIdMessagesMessageIDRedact"
  | "postConversationsIdRead"
  | "postConversationsIdSnooze"
  | "postConversationsIdTags"
  | "postCustomerCommandBindings"
  | "postCustomersIdAttributesKeyReveal"
  | "postCustomersIdTags"
  | "postCustomersMerge"
  | "postCustomersMergePreview"
  | "postCustomersMergesIdReverse"
  | "postEmailTemplatesKeyPreview"
  | "postFeedbackItemsIdComments"
  | "postFeedbackItemsIdVotes"
  | "postFieldDefinitions"
  | "postInboxes"
  | "postInvites"
  | "postInvitesRedeem"
  | "postJobsIdCancel"
  | "postJobsIdRetry"
  | "postKnowledgeBasesIdCollections"
  | "postNotificationsIdRead"
  | "postNotificationsReadAll"
  | "postPortalAuthLogout"
  | "postPortalAuthMagicLink"
  | "postPortalAuthMagicLinkRedeem"
  | "postPortals"
  | "postPortalTickets"
  | "postPortalTicketsIdFiles"
  | "postPortalTicketsIdReplies"
  | "postPublicFeedbackWorkspaceIDItemsIdVotes"
  | "postPublicKnowledgeBasesWorkspaceIDArticlesSlugFeedback"
  | "postRoles"
  | "postScimV20WorkspaceIDUsers"
  | "postTags"
  | "postTagsIdMerge"
  | "postTeams"
  | "postTicketsIdLinks"
  | "postTicketsIdTags"
  | "postWebhooksIdDeliveriesDeliveryIDReplay"
  | "postWebhooksIdRotateSecret"
  | "postWebhooksIdTest"
  | "postWidgetArticlesSlugFeedback"
  | "postWidgetConversations"
  | "postWidgetConversationsIdCommandsCommandIDAck"
  | "postWidgetConversationsIdFiles"
  | "postWidgetConversationsIdMessages"
  | "postWidgetEvents"
  | "postWidgetFeedbackBoardsSlugItems"
  | "postWidgetFeedbackItemsIdSubscription"
  | "postWidgetFeedbackItemsIdVotes"
  | "postWidgetFormsSlugFiles"
  | "postWidgetFormsSlugSubmissions"
  | "postWidgetIdentify"
  | "postWidgets"
  | "postWidgetsIdDomains"
  | "postWidgetsIdRollback"
  | "postWidgetVisitors"
  | "postWorkspaces"
  | "previewImport"
  | "previewWorkspaceExport"
  | "publishChangelogEntry"
  | "putCompaniesIdCustomersCustomerID"
  | "putConversationsIdFollowersMe"
  | "putEmailTemplatesKey"
  | "putFieldDefinitionsReorder"
  | "putInboxesIdDefault"
  | "putNotificationsPreferences"
  | "putScimV20WorkspaceIDUsersId"
  | "putTeamsIdMembersMemberId"
  | "putTicketsIdFieldValuesKey"
  | "putTicketsIdFollowersMe"
  | "putWidgetsId"
  | "putWidgetsIdDomains"
  | "receiveEmailDeliveryEvent"
  | "receiveInboundEmail"
  | "releaseWorkspaceLegalHold"
  | "removeEmailSuppression"
  | "searchPublicArticles"
  | "sendOperationalTestEmail"
  | "submitPortalForm"
  | "submitPublicForm"
  | "submitSurveyResponse"
  | "subscribeToFeedbackItem"
  | "unlinkConversation"
  | "unlinkFeedbackSupportWork"
  | "unsubscribeFromFeedbackItem"
  | "updateArticle"
  | "updateAutomationMacro"
  | "updateAutomationRule"
  | "updateChangelogEntry"
  | "updateConversation"
  | "updateCustomer"
  | "updateEmailMailbox"
  | "updateForm"
  | "updatePortalProfile"
  | "updateReport"
  | "updateReportSchedule"
  | "updateSavedView"
  | "updateSLACalendar"
  | "updateSurvey"
  | "updateTask"
  | "updateTicket"
  | "uploadFile"
  | "uploadPortabilityImportFile"
  | "uploadPortalFormFile"
  | "uploadPublicFormFile"
  | "useAutomationMacro"
  | "verifyPortalDomain";

export type ApiOperationCatalog = {
  "addPortalDomain": { method: "POST"; path: "/v1/portals/{id}/domains"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "bulkUpdateConversations": { method: "POST"; path: "/v1/conversations/bulk"; request: ApiBulkConversationUpdateRequest; response: ApiBulkConversationUpdateResult; };
  "confirmImport": { method: "POST"; path: "/v1/portability/imports/{id}/confirm"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "convertConversationToTicket": { method: "POST"; path: "/v1/conversations/{id}/ticket"; request: ApiCreateTicketRequest; response: ApiTicket; };
  "createAPIKey": { method: "POST"; path: "/v1/api-keys"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createArticle": { method: "POST"; path: "/v1/articles"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createAutomationMacro": { method: "POST"; path: "/v1/automation/macros"; request: ApiMacroInput; response: ApiMacro; };
  "createAutomationReply": { method: "POST"; path: "/v1/automation/replies"; request: ApiSavedReplyInput; response: ApiSavedReply; };
  "createAutomationRule": { method: "POST"; path: "/v1/automation/rules"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createChangelogEntry": { method: "POST"; path: "/v1/changelog"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createConversation": { method: "POST"; path: "/v1/conversations"; request: ApiCreateConversationRequest; response: ApiConversation; };
  "createConversationMessage": { method: "POST"; path: "/v1/conversations/{id}/messages"; request: ApiCreateConversationMessageRequest; response: ApiMessage; };
  "createEmailMailbox": { method: "POST"; path: "/v1/email/mailboxes"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createEvent": { method: "POST"; path: "/v1/events"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createExport": { method: "POST"; path: "/v1/portability/exports"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createFeedbackBoard": { method: "POST"; path: "/v1/feedback/boards"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createFeedbackItem": { method: "POST"; path: "/v1/feedback/boards/{id}/items"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createForm": { method: "POST"; path: "/v1/forms"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createImport": { method: "POST"; path: "/v1/portability/imports"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createKnowledgeBase": { method: "POST"; path: "/v1/knowledge-bases"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createPublicFeedbackComment": { method: "POST"; path: "/v1/public/feedback/{workspaceID}/items/{id}/comments"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createPublicFeedbackItem": { method: "POST"; path: "/v1/public/feedback/{workspaceID}/boards/{slug}/items"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createReport": { method: "POST"; path: "/v1/reports"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createReportSchedule": { method: "POST"; path: "/v1/reports/{id}/schedules"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createSavedView": { method: "POST"; path: "/v1/saved-views"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createSLACalendar": { method: "POST"; path: "/v1/sla/calendars"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createSLAPolicy": { method: "POST"; path: "/v1/sla/policies"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createSurvey": { method: "POST"; path: "/v1/surveys"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createTask": { method: "POST"; path: "/v1/tasks"; request: ApiTaskInput; response: ApiTask; };
  "createTicket": { method: "POST"; path: "/v1/tickets"; request: ApiCreateTicketRequest; response: ApiTicket; };
  "createWebhook": { method: "POST"; path: "/v1/webhooks"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "createWorkspaceLegalHold": { method: "POST"; path: "/v1/workspace/legal-holds"; request: ApiLegalHoldInput; response: ApiLegalHold; };
  "deleteApiKeysId": { method: "DELETE"; path: "/v1/api-keys/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteAttributeDefinitionsId": { method: "DELETE"; path: "/v1/attribute-definitions/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteAuthSessionsId": { method: "DELETE"; path: "/v1/auth/sessions/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteAuthTrustedDevicesId": { method: "DELETE"; path: "/v1/auth/trusted-devices/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteAutomationMacro": { method: "DELETE"; path: "/v1/automation/macros/{id}"; request: unknown; response: unknown; };
  "deleteCompaniesIdCustomersCustomerID": { method: "DELETE"; path: "/v1/companies/{id}/customers/{customerID}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteCompaniesIdTagsTagID": { method: "DELETE"; path: "/v1/companies/{id}/tags/{tagID}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteConversationsIdFollowersMe": { method: "DELETE"; path: "/v1/conversations/{id}/followers/me"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteConversationsIdTagsTagID": { method: "DELETE"; path: "/v1/conversations/{id}/tags/{tagID}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteCustomersId": { method: "DELETE"; path: "/v1/customers/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteCustomersIdTagsTagID": { method: "DELETE"; path: "/v1/customers/{id}/tags/{tagID}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteEmailMailbox": { method: "DELETE"; path: "/v1/email/mailboxes/{id}"; request: unknown; response: unknown; };
  "deleteEmailTemplatesKey": { method: "DELETE"; path: "/v1/email/templates/{key}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteFieldDefinitionsId": { method: "DELETE"; path: "/v1/field-definitions/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteForm": { method: "DELETE"; path: "/v1/forms/{id}"; request: unknown; response: unknown; };
  "deleteInboxesId": { method: "DELETE"; path: "/v1/inboxes/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteInvitesId": { method: "DELETE"; path: "/v1/invites/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteMembersId": { method: "DELETE"; path: "/v1/members/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deletePortalCustomerData": { method: "POST"; path: "/v1/portal/me/delete"; request: {
  [key: string]: unknown;
}; response: unknown; };
  "deletePortalDomain": { method: "DELETE"; path: "/v1/portals/{id}/domains/{domainID}"; request: unknown; response: unknown; };
  "deleteReport": { method: "DELETE"; path: "/v1/reports/{id}"; request: unknown; response: unknown; };
  "deleteReportSchedule": { method: "DELETE"; path: "/v1/reports/{id}/schedules/{scheduleID}"; request: unknown; response: unknown; };
  "deleteRolesId": { method: "DELETE"; path: "/v1/roles/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteSavedView": { method: "DELETE"; path: "/v1/saved-views/{id}"; request: unknown; response: unknown; };
  "deleteScimV20WorkspaceIDUsersId": { method: "DELETE"; path: "/v1/scim/v2.0/{workspaceID}/Users/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteTagsId": { method: "DELETE"; path: "/v1/tags/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteTeamsId": { method: "DELETE"; path: "/v1/teams/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteTeamsIdMembersMemberId": { method: "DELETE"; path: "/v1/teams/{id}/members/{memberId}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteTicketsIdFollowersMe": { method: "DELETE"; path: "/v1/tickets/{id}/followers/me"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteTicketsIdLinksTargetID": { method: "DELETE"; path: "/v1/tickets/{id}/links/{targetID}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteTicketsIdTagsTagID": { method: "DELETE"; path: "/v1/tickets/{id}/tags/{tagID}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteWebhooksId": { method: "DELETE"; path: "/v1/webhooks/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteWidgetFeedbackItemsIdSubscription": { method: "DELETE"; path: "/v1/widget/feedback/items/{id}/subscription"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteWidgetsId": { method: "DELETE"; path: "/v1/widgets/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "deleteWidgetsIdDomainsDomainID": { method: "DELETE"; path: "/v1/widgets/{id}/domains/{domainID}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "downloadFile": { method: "GET"; path: "/v1/files/{id}"; request: unknown; response: unknown; };
  "exportAnalyticsCsv": { method: "GET"; path: "/v1/analytics/export.csv"; request: unknown; response: unknown; };
  "exportAuditLogs": { method: "GET"; path: "/v1/audit-logs/export.csv"; request: unknown; response: unknown; };
  "exportCompanies": { method: "GET"; path: "/v1/companies/export"; request: unknown; response: unknown; };
  "exportCustomers": { method: "GET"; path: "/v1/customers/export"; request: unknown; response: unknown; };
  "exportPortalCustomerData": { method: "GET"; path: "/v1/portal/me/export"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "exportSurveyResponses": { method: "GET"; path: "/v1/surveys/{id}/responses.csv"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAnalyticsSummary": { method: "GET"; path: "/v1/analytics/summary"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAnalyticsWorkload": { method: "GET"; path: "/v1/analytics/workload"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getArticle": { method: "GET"; path: "/v1/articles/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAttributeDefinitions": { method: "GET"; path: "/v1/attribute-definitions"; request: unknown; response: ApiAttributeDefinitionPage; };
  "getAuthMe": { method: "GET"; path: "/v1/auth/me"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAuthOauthProviderCallback": { method: "GET"; path: "/v1/auth/oauth/{provider}/callback"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAuthOauthProviders": { method: "GET"; path: "/v1/auth/oauth/providers"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAuthOauthProviderStart": { method: "GET"; path: "/v1/auth/oauth/{provider}/start"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAuthSessions": { method: "GET"; path: "/v1/auth/sessions"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAuthTotp": { method: "GET"; path: "/v1/auth/totp"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAuthTrustedDevices": { method: "GET"; path: "/v1/auth/trusted-devices"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getAutomationMacro": { method: "GET"; path: "/v1/automation/macros/{id}"; request: unknown; response: ApiMacro; };
  "getAutomationRule": { method: "GET"; path: "/v1/automation/rules/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getBootstrap": { method: "GET"; path: "/v1/bootstrap"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getChangelogEntry": { method: "GET"; path: "/v1/changelog/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getCompanies": { method: "GET"; path: "/v1/companies"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getCompaniesId": { method: "GET"; path: "/v1/companies/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getCompaniesIdCustomers": { method: "GET"; path: "/v1/companies/{id}/customers"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getConversation": { method: "GET"; path: "/v1/conversations/{id}"; request: unknown; response: ApiConversation; };
  "getConversationsCounts": { method: "GET"; path: "/v1/conversations/counts"; request: unknown; response: ApiConversationCounts; };
  "getConversationsIdFollowers": { method: "GET"; path: "/v1/conversations/{id}/followers"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getConversationsIdTranscript": { method: "GET"; path: "/v1/conversations/{id}/transcript"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getCustomer": { method: "GET"; path: "/v1/customers/{id}"; request: unknown; response: ApiCustomer; };
  "getCustomer360": { method: "GET"; path: "/v1/customers/{id}/360"; request: unknown; response: ApiCustomer360; };
  "getCustomerCommandBindings": { method: "GET"; path: "/v1/customer-command-bindings"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getCustomersIdExport": { method: "GET"; path: "/v1/customers/{id}/export"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getCustomersIdSessions": { method: "GET"; path: "/v1/customers/{id}/sessions"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getCustomersIdTimeline": { method: "GET"; path: "/v1/customers/{id}/timeline"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getEmailStatus": { method: "GET"; path: "/v1/email/status"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getEmailTemplates": { method: "GET"; path: "/v1/email/templates"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getExport": { method: "GET"; path: "/v1/portability/exports/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getExportManifest": { method: "GET"; path: "/v1/portability/exports/{id}/manifest"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getFeedbackBoardsId": { method: "GET"; path: "/v1/feedback/boards/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getFeedbackItemsId": { method: "GET"; path: "/v1/feedback/items/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getFeedbackItemsIdComments": { method: "GET"; path: "/v1/feedback/items/{id}/comments"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getFeedbackRoadmap": { method: "GET"; path: "/v1/feedback/roadmap"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getFieldDefinitions": { method: "GET"; path: "/v1/field-definitions"; request: unknown; response: ApiFieldDefinitionPage; };
  "getForm": { method: "GET"; path: "/v1/forms/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getImport": { method: "GET"; path: "/v1/portability/imports/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getInboxes": { method: "GET"; path: "/v1/inboxes"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getInboxesId": { method: "GET"; path: "/v1/inboxes/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getInvites": { method: "GET"; path: "/v1/invites"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getInvitesLookupToken": { method: "GET"; path: "/v1/invites/lookup/{token}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getJobSummary": { method: "GET"; path: "/v1/jobs/summary"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getKnowledgeBasesIdCollections": { method: "GET"; path: "/v1/knowledge-bases/{id}/collections"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getMembers": { method: "GET"; path: "/v1/members"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getMeta": { method: "GET"; path: "/v1/meta"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getNotifications": { method: "GET"; path: "/v1/notifications"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getNotificationsCount": { method: "GET"; path: "/v1/notifications/count"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getNotificationsPreferences": { method: "GET"; path: "/v1/notifications/preferences"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getOpenapiJson": { method: "GET"; path: "/v1/openapi.json"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getOperationalSummary": { method: "GET"; path: "/v1/ops/summary"; request: unknown; response: ApiOpsSummary; };
  "getPortalBootstrap": { method: "GET"; path: "/v1/portal/bootstrap"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPortalFilesId": { method: "GET"; path: "/v1/portal/files/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPortalForm": { method: "GET"; path: "/v1/portal/forms/{slug}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPortalProfile": { method: "GET"; path: "/v1/portal/me"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPortals": { method: "GET"; path: "/v1/portals"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPortalsId": { method: "GET"; path: "/v1/portals/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPortalTickets": { method: "GET"; path: "/v1/portal/tickets"; request: unknown; response: ApiPortalTicketPage; };
  "getPortalTicketsId": { method: "GET"; path: "/v1/portal/tickets/{id}"; request: unknown; response: ApiPortalTicketDetail; };
  "getPublicFeedbackItem": { method: "GET"; path: "/v1/public/feedback/{workspaceID}/items/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPublicFeedbackWorkspaceIDBoards": { method: "GET"; path: "/v1/public/feedback/{workspaceID}/boards"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPublicForm": { method: "GET"; path: "/v1/public/forms/{workspaceID}/{slug}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPublicKnowledgeBasesWorkspaceIDArticlesSlug": { method: "GET"; path: "/v1/public/knowledge-bases/{workspaceID}/articles/{slug}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getPublicSurveysWorkspaceIDId": { method: "GET"; path: "/v1/public/surveys/{workspaceID}/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getReport": { method: "GET"; path: "/v1/reports/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getRoles": { method: "GET"; path: "/v1/roles"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getSavedView": { method: "GET"; path: "/v1/saved-views/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getScimV20WorkspaceIDUsers": { method: "GET"; path: "/v1/scim/v2.0/{workspaceID}/Users"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getScimV20WorkspaceIDUsersId": { method: "GET"; path: "/v1/scim/v2.0/{workspaceID}/Users/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getSearch": { method: "GET"; path: "/v1/search"; request: unknown; response: ApiSearchPage; };
  "getSetupState": { method: "GET"; path: "/v1/setup/state"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getSLACalendar": { method: "GET"; path: "/v1/sla/calendars/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getSlaPoliciesId": { method: "GET"; path: "/v1/sla/policies/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getSurvey": { method: "GET"; path: "/v1/surveys/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getSurveysIdSummary": { method: "GET"; path: "/v1/surveys/{id}/summary"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getTags": { method: "GET"; path: "/v1/tags"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getTask": { method: "GET"; path: "/v1/tasks/{id}"; request: unknown; response: ApiTask; };
  "getTeams": { method: "GET"; path: "/v1/teams"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getTicket": { method: "GET"; path: "/v1/tickets/{id}"; request: unknown; response: ApiTicket; };
  "getTicketsDuplicates": { method: "GET"; path: "/v1/tickets/duplicates"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getTicketsExport": { method: "GET"; path: "/v1/tickets/export"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getTicketsIdActivity": { method: "GET"; path: "/v1/tickets/{id}/activity"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getTicketsIdChildren": { method: "GET"; path: "/v1/tickets/{id}/children"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getTicketsIdFollowers": { method: "GET"; path: "/v1/tickets/{id}/followers"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getTicketsIdLinks": { method: "GET"; path: "/v1/tickets/{id}/links"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getVisitorsIdContext": { method: "GET"; path: "/v1/visitors/{id}/context"; request: unknown; response: ApiVisitorContext; };
  "getWebhooksId": { method: "GET"; path: "/v1/webhooks/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWebhooksIdDeliveries": { method: "GET"; path: "/v1/webhooks/{id}/deliveries"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetArticles": { method: "GET"; path: "/v1/widget/articles"; request: unknown; response: ApiWidgetArticlePage; };
  "getWidgetArticlesSlug": { method: "GET"; path: "/v1/widget/articles/{slug}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetConfig": { method: "GET"; path: "/v1/widget/config"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetConversationsIdCommands": { method: "GET"; path: "/v1/widget/conversations/{id}/commands"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetConversationsIdFilesFileID": { method: "GET"; path: "/v1/widget/conversations/{id}/files/{fileID}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetConversationsIdMessages": { method: "GET"; path: "/v1/widget/conversations/{id}/messages"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetFeedbackBoards": { method: "GET"; path: "/v1/widget/feedback/boards"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetFeedbackBoardsSlugItems": { method: "GET"; path: "/v1/widget/feedback/boards/{slug}/items"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetForms": { method: "GET"; path: "/v1/widget/forms"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetFormsSlug": { method: "GET"; path: "/v1/widget/forms/{slug}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgets": { method: "GET"; path: "/v1/widgets"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetsId": { method: "GET"; path: "/v1/widgets/{id}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetsIdDomains": { method: "GET"; path: "/v1/widgets/{id}/domains"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetsIdIdentitySecret": { method: "GET"; path: "/v1/widgets/{id}/identity-secret"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWidgetsIdVersions": { method: "GET"; path: "/v1/widgets/{id}/versions"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWorkspaceSettings": { method: "GET"; path: "/v1/workspace/settings"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "getWorkspaceUsage": { method: "GET"; path: "/v1/workspace/usage"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "linkConversation": { method: "POST"; path: "/v1/conversations/{id}/links"; request: ApiConversationLinkInput; response: ApiConversationLink; };
  "linkFeedbackSupportWork": { method: "POST"; path: "/v1/feedback/items/{id}/links"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "listAllFeedbackItems": { method: "GET"; path: "/v1/feedback/items"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listAnalyticsNoResultSearches": { method: "GET"; path: "/v1/analytics/searches/no-results"; request: unknown; response: ApiAnalyticsSearchTermPage; };
  "listAnalyticsRollups": { method: "GET"; path: "/v1/analytics/rollups"; request: unknown; response: ApiAnalyticsRollupPage; };
  "listAPIKeys": { method: "GET"; path: "/v1/api-keys"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listArticleRevisions": { method: "GET"; path: "/v1/articles/{id}/revisions"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listArticles": { method: "GET"; path: "/v1/articles"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listAuditLogs": { method: "GET"; path: "/v1/audit-logs"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listAutomationExecutions": { method: "GET"; path: "/v1/automation/executions"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listAutomationMacros": { method: "GET"; path: "/v1/automation/macros"; request: unknown; response: ApiMacroPage; };
  "listAutomationReplies": { method: "GET"; path: "/v1/automation/replies"; request: unknown; response: ApiSavedReplyPage; };
  "listAutomationRules": { method: "GET"; path: "/v1/automation/rules"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listChangelogEntries": { method: "GET"; path: "/v1/changelog"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listConversationLinks": { method: "GET"; path: "/v1/conversations/{id}/links"; request: unknown; response: ApiConversationLinkPage; };
  "listConversationMessages": { method: "GET"; path: "/v1/conversations/{id}/messages"; request: unknown; response: ApiMessagePage; };
  "listConversations": { method: "GET"; path: "/v1/conversations"; request: unknown; response: ApiConversationPage; };
  "listCustomers": { method: "GET"; path: "/v1/customers"; request: unknown; response: ApiCustomerPage; };
  "listEmailDeliveryEvents": { method: "GET"; path: "/v1/email/mailboxes/{id}/delivery-events"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listEmailMailboxes": { method: "GET"; path: "/v1/email/mailboxes"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listEmailSuppressions": { method: "GET"; path: "/v1/email/suppressions"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listEvents": { method: "GET"; path: "/v1/events"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listExports": { method: "GET"; path: "/v1/portability/exports"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listFeedbackBoards": { method: "GET"; path: "/v1/feedback/boards"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listFeedbackItems": { method: "GET"; path: "/v1/feedback/boards/{id}/items"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listFeedbackLinks": { method: "GET"; path: "/v1/feedback/items/{id}/links"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listForms": { method: "GET"; path: "/v1/forms"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listImports": { method: "GET"; path: "/v1/portability/imports"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listJobs": { method: "GET"; path: "/v1/jobs"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listKnowledgeBases": { method: "GET"; path: "/v1/knowledge-bases"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listMailboxEmailSuppressions": { method: "GET"; path: "/v1/email/mailboxes/{id}/suppressions"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listMetricDefinitions": { method: "GET"; path: "/v1/analytics/metrics"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listPortalDomains": { method: "GET"; path: "/v1/portals/{id}/domains"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listPortalForms": { method: "GET"; path: "/v1/portal/forms"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listPublicChangelogEntries": { method: "GET"; path: "/v1/public/changelog/{workspaceID}"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listPublicFeedbackComments": { method: "GET"; path: "/v1/public/feedback/{workspaceID}/items/{id}/comments"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listPublicFeedbackItems": { method: "GET"; path: "/v1/public/feedback/{workspaceID}/boards/{slug}/items"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listReports": { method: "GET"; path: "/v1/reports"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listReportSchedules": { method: "GET"; path: "/v1/reports/{id}/schedules"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listSavedViews": { method: "GET"; path: "/v1/saved-views"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listSLACalendars": { method: "GET"; path: "/v1/sla/calendars"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listSLAInstances": { method: "GET"; path: "/v1/sla/instances"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listSLAPolicies": { method: "GET"; path: "/v1/sla/policies"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listSurveyResponses": { method: "GET"; path: "/v1/surveys/{id}/responses"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listSurveys": { method: "GET"; path: "/v1/surveys"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listTasks": { method: "GET"; path: "/v1/tasks"; request: unknown; response: ApiTaskPage; };
  "listTickets": { method: "GET"; path: "/v1/tickets"; request: unknown; response: ApiTicketPage; };
  "listWebhooks": { method: "GET"; path: "/v1/webhooks"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "listWorkspaceLegalHolds": { method: "GET"; path: "/v1/workspace/legal-holds"; request: unknown; response: ApiLegalHoldPage; };
  "mergeFeedbackItem": { method: "POST"; path: "/v1/feedback/items/{id}/merge"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchAttributeDefinitionsId": { method: "PATCH"; path: "/v1/attribute-definitions/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchAuthProfile": { method: "PATCH"; path: "/v1/auth/profile"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchCompaniesId": { method: "PATCH"; path: "/v1/companies/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchCompaniesIdAttributes": { method: "PATCH"; path: "/v1/companies/{id}/attributes"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchConversationsIdAssignee": { method: "PATCH"; path: "/v1/conversations/{id}/assignee"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchConversationsIdInbox": { method: "PATCH"; path: "/v1/conversations/{id}/inbox"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchConversationsIdMessagesMessageID": { method: "PATCH"; path: "/v1/conversations/{id}/messages/{messageID}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchConversationsIdPriority": { method: "PATCH"; path: "/v1/conversations/{id}/priority"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchConversationsIdState": { method: "PATCH"; path: "/v1/conversations/{id}/state"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchConversationsIdTeam": { method: "PATCH"; path: "/v1/conversations/{id}/team"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchCustomerCommandBindingsId": { method: "PATCH"; path: "/v1/customer-command-bindings/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchCustomersIdAttributes": { method: "PATCH"; path: "/v1/customers/{id}/attributes"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchCustomersIdOwner": { method: "PATCH"; path: "/v1/customers/{id}/owner"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchFeedbackItemsIdStatus": { method: "PATCH"; path: "/v1/feedback/items/{id}/status"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchFieldDefinitionsId": { method: "PATCH"; path: "/v1/field-definitions/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchInboxesId": { method: "PATCH"; path: "/v1/inboxes/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchMembersIdCapabilities": { method: "PATCH"; path: "/v1/members/{id}/capabilities"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchMembersIdRole": { method: "PATCH"; path: "/v1/members/{id}/role"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchMembersMeAcceptingConversations": { method: "PATCH"; path: "/v1/members/me/accepting-conversations"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchMembersMePresence": { method: "PATCH"; path: "/v1/members/me/presence"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchPortalsId": { method: "PATCH"; path: "/v1/portals/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchRolesId": { method: "PATCH"; path: "/v1/roles/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchScimV20WorkspaceIDUsersId": { method: "PATCH"; path: "/v1/scim/v2.0/{workspaceID}/Users/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchSlaPoliciesId": { method: "PATCH"; path: "/v1/sla/policies/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchTeamsId": { method: "PATCH"; path: "/v1/teams/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchTicketsIdAssignee": { method: "PATCH"; path: "/v1/tickets/{id}/assignee"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchTicketsIdCustomer": { method: "PATCH"; path: "/v1/tickets/{id}/customer"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchTicketsIdDue": { method: "PATCH"; path: "/v1/tickets/{id}/due"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchTicketsIdInbox": { method: "PATCH"; path: "/v1/tickets/{id}/inbox"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchTicketsIdParent": { method: "PATCH"; path: "/v1/tickets/{id}/parent"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchTicketsIdPriority": { method: "PATCH"; path: "/v1/tickets/{id}/priority"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchTicketsIdStatus": { method: "PATCH"; path: "/v1/tickets/{id}/status"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchTicketsIdTeam": { method: "PATCH"; path: "/v1/tickets/{id}/team"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchWebhooksId": { method: "PATCH"; path: "/v1/webhooks/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchWorkspaceBranding": { method: "PATCH"; path: "/v1/workspace/branding"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchWorkspaceGeneral": { method: "PATCH"; path: "/v1/workspace/general"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchWorkspacePrivacy": { method: "PATCH"; path: "/v1/workspace/privacy"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "patchWorkspaceSecurity": { method: "PATCH"; path: "/v1/workspace/security"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postApiKeysIdRotate": { method: "POST"; path: "/v1/api-keys/{id}/rotate"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postArticlesIdPublish": { method: "POST"; path: "/v1/articles/{id}/publish"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAttributeDefinitions": { method: "POST"; path: "/v1/attribute-definitions"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthLogin": { method: "POST"; path: "/v1/auth/login"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthLogout": { method: "POST"; path: "/v1/auth/logout"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthMagicLink": { method: "POST"; path: "/v1/auth/magic-link"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthMagicLinkRedeem": { method: "POST"; path: "/v1/auth/magic-link/redeem"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthPasswordChange": { method: "POST"; path: "/v1/auth/password/change"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthPasswordForgot": { method: "POST"; path: "/v1/auth/password/forgot"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthPasswordReset": { method: "POST"; path: "/v1/auth/password/reset"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthSessionsRevokeOthers": { method: "POST"; path: "/v1/auth/sessions/revoke-others"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthSignup": { method: "POST"; path: "/v1/auth/signup"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthTotpBegin": { method: "POST"; path: "/v1/auth/totp/begin"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthTotpChallenge": { method: "POST"; path: "/v1/auth/totp/challenge"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthTotpComplete": { method: "POST"; path: "/v1/auth/totp/complete"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthTotpDisable": { method: "POST"; path: "/v1/auth/totp/disable"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthTrustedDevicesRevokeAll": { method: "POST"; path: "/v1/auth/trusted-devices/revoke-all"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthVerifyEmail": { method: "POST"; path: "/v1/auth/verify-email"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAuthVerifyEmailResend": { method: "POST"; path: "/v1/auth/verify-email/resend"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAutomationRepliesIdUse": { method: "POST"; path: "/v1/automation/replies/{id}/use"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postAutomationRulesIdDryRun": { method: "POST"; path: "/v1/automation/rules/{id}/dry-run"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postBlockedContacts": { method: "POST"; path: "/v1/blocked-contacts"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postCompanies": { method: "POST"; path: "/v1/companies"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postCompaniesIdTags": { method: "POST"; path: "/v1/companies/{id}/tags"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postConversationsIdCustomerCommands": { method: "POST"; path: "/v1/conversations/{id}/customer-commands"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postConversationsIdMerge": { method: "POST"; path: "/v1/conversations/{id}/merge"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postConversationsIdMessagesMessageIDRedact": { method: "POST"; path: "/v1/conversations/{id}/messages/{messageID}/redact"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postConversationsIdRead": { method: "POST"; path: "/v1/conversations/{id}/read"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postConversationsIdSnooze": { method: "POST"; path: "/v1/conversations/{id}/snooze"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postConversationsIdTags": { method: "POST"; path: "/v1/conversations/{id}/tags"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postCustomerCommandBindings": { method: "POST"; path: "/v1/customer-command-bindings"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postCustomersIdAttributesKeyReveal": { method: "POST"; path: "/v1/customers/{id}/attributes/{key}/reveal"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postCustomersIdTags": { method: "POST"; path: "/v1/customers/{id}/tags"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postCustomersMerge": { method: "POST"; path: "/v1/customers/merge"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postCustomersMergePreview": { method: "POST"; path: "/v1/customers/merge/preview"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postCustomersMergesIdReverse": { method: "POST"; path: "/v1/customers/merges/{id}/reverse"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postEmailTemplatesKeyPreview": { method: "POST"; path: "/v1/email/templates/{key}/preview"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postFeedbackItemsIdComments": { method: "POST"; path: "/v1/feedback/items/{id}/comments"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postFeedbackItemsIdVotes": { method: "POST"; path: "/v1/feedback/items/{id}/votes"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postFieldDefinitions": { method: "POST"; path: "/v1/field-definitions"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postInboxes": { method: "POST"; path: "/v1/inboxes"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postInvites": { method: "POST"; path: "/v1/invites"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postInvitesRedeem": { method: "POST"; path: "/v1/invites/redeem"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postJobsIdCancel": { method: "POST"; path: "/v1/jobs/{id}/cancel"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postJobsIdRetry": { method: "POST"; path: "/v1/jobs/{id}/retry"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postKnowledgeBasesIdCollections": { method: "POST"; path: "/v1/knowledge-bases/{id}/collections"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postNotificationsIdRead": { method: "POST"; path: "/v1/notifications/{id}/read"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postNotificationsReadAll": { method: "POST"; path: "/v1/notifications/read-all"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postPortalAuthLogout": { method: "POST"; path: "/v1/portal/auth/logout"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postPortalAuthMagicLink": { method: "POST"; path: "/v1/portal/auth/magic-link"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postPortalAuthMagicLinkRedeem": { method: "POST"; path: "/v1/portal/auth/magic-link/redeem"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postPortals": { method: "POST"; path: "/v1/portals"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postPortalTickets": { method: "POST"; path: "/v1/portal/tickets"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postPortalTicketsIdFiles": { method: "POST"; path: "/v1/portal/tickets/{id}/files"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postPortalTicketsIdReplies": { method: "POST"; path: "/v1/portal/tickets/{id}/replies"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postPublicFeedbackWorkspaceIDItemsIdVotes": { method: "POST"; path: "/v1/public/feedback/{workspaceID}/items/{id}/votes"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postPublicKnowledgeBasesWorkspaceIDArticlesSlugFeedback": { method: "POST"; path: "/v1/public/knowledge-bases/{workspaceID}/articles/{slug}/feedback"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postRoles": { method: "POST"; path: "/v1/roles"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postScimV20WorkspaceIDUsers": { method: "POST"; path: "/v1/scim/v2.0/{workspaceID}/Users"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postTags": { method: "POST"; path: "/v1/tags"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postTagsIdMerge": { method: "POST"; path: "/v1/tags/{id}/merge"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postTeams": { method: "POST"; path: "/v1/teams"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postTicketsIdLinks": { method: "POST"; path: "/v1/tickets/{id}/links"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postTicketsIdTags": { method: "POST"; path: "/v1/tickets/{id}/tags"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWebhooksIdDeliveriesDeliveryIDReplay": { method: "POST"; path: "/v1/webhooks/{id}/deliveries/{deliveryID}/replay"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWebhooksIdRotateSecret": { method: "POST"; path: "/v1/webhooks/{id}/rotate-secret"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWebhooksIdTest": { method: "POST"; path: "/v1/webhooks/{id}/test"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetArticlesSlugFeedback": { method: "POST"; path: "/v1/widget/articles/{slug}/feedback"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetConversations": { method: "POST"; path: "/v1/widget/conversations"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetConversationsIdCommandsCommandIDAck": { method: "POST"; path: "/v1/widget/conversations/{id}/commands/{commandID}/ack"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetConversationsIdFiles": { method: "POST"; path: "/v1/widget/conversations/{id}/files"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetConversationsIdMessages": { method: "POST"; path: "/v1/widget/conversations/{id}/messages"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetEvents": { method: "POST"; path: "/v1/widget/events"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetFeedbackBoardsSlugItems": { method: "POST"; path: "/v1/widget/feedback/boards/{slug}/items"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetFeedbackItemsIdSubscription": { method: "POST"; path: "/v1/widget/feedback/items/{id}/subscription"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetFeedbackItemsIdVotes": { method: "POST"; path: "/v1/widget/feedback/items/{id}/votes"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetFormsSlugFiles": { method: "POST"; path: "/v1/widget/forms/{slug}/files"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetFormsSlugSubmissions": { method: "POST"; path: "/v1/widget/forms/{slug}/submissions"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetIdentify": { method: "POST"; path: "/v1/widget/identify"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgets": { method: "POST"; path: "/v1/widgets"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetsIdDomains": { method: "POST"; path: "/v1/widgets/{id}/domains"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetsIdRollback": { method: "POST"; path: "/v1/widgets/{id}/rollback"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWidgetVisitors": { method: "POST"; path: "/v1/widget/visitors"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "postWorkspaces": { method: "POST"; path: "/v1/workspaces"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "previewImport": { method: "POST"; path: "/v1/portability/imports/{id}/preview"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "previewWorkspaceExport": { method: "POST"; path: "/v1/portability/exports/preview"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "publishChangelogEntry": { method: "POST"; path: "/v1/changelog/{id}/publish"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putCompaniesIdCustomersCustomerID": { method: "PUT"; path: "/v1/companies/{id}/customers/{customerID}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putConversationsIdFollowersMe": { method: "PUT"; path: "/v1/conversations/{id}/followers/me"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putEmailTemplatesKey": { method: "PUT"; path: "/v1/email/templates/{key}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putFieldDefinitionsReorder": { method: "PUT"; path: "/v1/field-definitions/reorder"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putInboxesIdDefault": { method: "PUT"; path: "/v1/inboxes/{id}/default"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putNotificationsPreferences": { method: "PUT"; path: "/v1/notifications/preferences"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putScimV20WorkspaceIDUsersId": { method: "PUT"; path: "/v1/scim/v2.0/{workspaceID}/Users/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putTeamsIdMembersMemberId": { method: "PUT"; path: "/v1/teams/{id}/members/{memberId}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putTicketsIdFieldValuesKey": { method: "PUT"; path: "/v1/tickets/{id}/field-values/{key}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putTicketsIdFollowersMe": { method: "PUT"; path: "/v1/tickets/{id}/followers/me"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putWidgetsId": { method: "PUT"; path: "/v1/widgets/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "putWidgetsIdDomains": { method: "PUT"; path: "/v1/widgets/{id}/domains"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "receiveEmailDeliveryEvent": { method: "POST"; path: "/v1/email/delivery/{provider}/{mailboxID}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "receiveInboundEmail": { method: "POST"; path: "/v1/email/inbound/{provider}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "releaseWorkspaceLegalHold": { method: "POST"; path: "/v1/workspace/legal-holds/{id}/release"; request: unknown; response: ApiLegalHold; };
  "removeEmailSuppression": { method: "DELETE"; path: "/v1/email/mailboxes/{id}/suppressions/{address}"; request: unknown; response: unknown; };
  "searchPublicArticles": { method: "GET"; path: "/v1/public/knowledge-bases/{workspaceID}/search"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "sendOperationalTestEmail": { method: "POST"; path: "/v1/ops/test-email"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "submitPortalForm": { method: "POST"; path: "/v1/portal/forms/{slug}/submissions"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "submitPublicForm": { method: "POST"; path: "/v1/public/forms/{workspaceID}/{slug}/submissions"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "submitSurveyResponse": { method: "POST"; path: "/v1/public/surveys/{workspaceID}/{id}/responses"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "subscribeToFeedbackItem": { method: "POST"; path: "/v1/public/feedback/{workspaceID}/items/{id}/subscription"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "unlinkConversation": { method: "DELETE"; path: "/v1/conversations/{id}/links/{targetID}"; request: unknown; response: unknown; };
  "unlinkFeedbackSupportWork": { method: "DELETE"; path: "/v1/feedback/items/{id}/links/{linkID}"; request: unknown; response: unknown; };
  "unsubscribeFromFeedbackItem": { method: "DELETE"; path: "/v1/public/feedback/{workspaceID}/items/{id}/subscription"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "updateArticle": { method: "PATCH"; path: "/v1/articles/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateAutomationMacro": { method: "PATCH"; path: "/v1/automation/macros/{id}"; request: ApiMacroInput; response: ApiMacro; };
  "updateAutomationRule": { method: "PATCH"; path: "/v1/automation/rules/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateChangelogEntry": { method: "PATCH"; path: "/v1/changelog/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateConversation": { method: "PATCH"; path: "/v1/conversations/{id}"; request: ApiUpdateConversationRequest; response: ApiConversation; };
  "updateCustomer": { method: "PATCH"; path: "/v1/customers/{id}"; request: ApiUpdateCustomerRequest; response: ApiCustomer; };
  "updateEmailMailbox": { method: "PATCH"; path: "/v1/email/mailboxes/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateForm": { method: "PATCH"; path: "/v1/forms/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updatePortalProfile": { method: "PATCH"; path: "/v1/portal/me"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateReport": { method: "PATCH"; path: "/v1/reports/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateReportSchedule": { method: "PATCH"; path: "/v1/reports/{id}/schedules/{scheduleID}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateSavedView": { method: "PATCH"; path: "/v1/saved-views/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateSLACalendar": { method: "PATCH"; path: "/v1/sla/calendars/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateSurvey": { method: "PATCH"; path: "/v1/surveys/{id}"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
  "updateTask": { method: "PATCH"; path: "/v1/tasks/{id}"; request: ApiUpdateTaskRequest; response: ApiTask; };
  "updateTicket": { method: "PATCH"; path: "/v1/tickets/{id}"; request: ApiUpdateTicketRequest; response: ApiTicket; };
  "uploadFile": { method: "POST"; path: "/v1/files"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "uploadPortabilityImportFile": { method: "POST"; path: "/v1/portability/import-files"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "uploadPortalFormFile": { method: "POST"; path: "/v1/portal/forms/{slug}/files"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "uploadPublicFormFile": { method: "POST"; path: "/v1/public/forms/{workspaceID}/{slug}/files"; request: unknown; response: {
  [key: string]: unknown;
}; };
  "useAutomationMacro": { method: "POST"; path: "/v1/automation/macros/{id}/use"; request: ApiMacroExecutionRequest; response: ApiMacroExecution; };
  "verifyPortalDomain": { method: "POST"; path: "/v1/portals/{id}/domains/{domainID}/verify"; request: {
  [key: string]: unknown;
}; response: {
  [key: string]: unknown;
}; };
};

export type ApiRequest<TOperation extends ApiOperationId> = ApiOperationCatalog[TOperation]["request"];
export type ApiResponse<TOperation extends ApiOperationId> = ApiOperationCatalog[TOperation]["response"];

