import { ApiError, Badge, Button, Card, CardBody, EmptyState, Page, PageBody, PageHeader, Pagination, Select, api, formatDate, useInfinite } from "@hubchat/shared";
import type { Paginated } from "@hubchat/shared";
import { ScrollText } from "lucide-react";
import { useState } from "react";

type Execution = { id: string; rule_id: string; rule_version: number; subject_type: string; subject_id: string; outcome: string; depth: number; causation_id: string | null; actions_applied: Array<unknown>; error: string; duration_ms: number; dry_run: boolean; occurred_at: string };

export default function ExecutionLog() {
  const [filter, setFilter] = useState("");
  const query = useInfinite<Execution>(["automation-executions", filter], (cursor, signal) => api.get<Paginated<Execution>>("/automation/executions?limit=25" + (filter ? "&rule_id=" + encodeURIComponent(filter) : "") + (cursor ? "&cursor=" + encodeURIComponent(cursor) : ""), { signal }));
  return <Page><PageHeader title="Execution log" description="Every evaluation is retained with outcome, causation depth, duration, and applied actions." /><PageBody><div className="mb-4 w-56"><Select size="sm" value={filter} onValueChange={setFilter} options={[{ value: "", label: "All rules" }]} /></div>{query.isLoading ? <p className="text-sm text-fg-muted">Loading execution log…</p> : query.error ? <EmptyState icon={ScrollText} title="Execution log unavailable" description={query.error instanceof ApiError ? query.error.message : "Try again in a moment."} action={<Button variant="secondary" size="sm" onClick={query.refetch}>Try again</Button>} /> : <Card><CardBody className="p-0">{query.items.length === 0 ? <p className="p-8 text-center text-sm text-fg-muted">No executions yet.</p> : <ul className="divide-y divide-line-subtle">{query.items.map((item) => <li key={item.id} className="flex flex-wrap items-center gap-3 px-4 py-3"><Badge tone={item.outcome === "matched" ? "success" : item.outcome === "failed" ? "danger" : "neutral"}>{item.outcome}</Badge><div className="min-w-0 flex-1"><p className="text-sm text-fg">{item.rule_id} · {item.actions_applied.length} actions</p><p className="mt-0.5 text-xs text-fg-muted">{item.subject_type || "event"} {item.subject_id || ""} · depth {item.depth} · {item.duration_ms}ms{item.dry_run ? " · dry run" : ""}</p>{item.error && <p className="mt-1 text-xs text-danger">{item.error}</p>}</div><time className="text-2xs text-fg-muted">{formatDate(item.occurred_at)}</time></li>)}</ul>}<Pagination hasPrevious={false} hasNext={query.hasMore} onPrevious={() => undefined} onNext={() => void query.fetchNext()} summary={query.items.length + " execution" + (query.items.length === 1 ? "" : "s") + " loaded"} /></CardBody></Card>}</PageBody></Page>;
}
