import { ApiError, Avatar, Badge, Button, Card, CardBody, EmptyState, Textarea, api, formatDate, idempotencyKey, useMutation, useQuery, type FeedbackComment, type FeedbackItem } from "@hubchat/shared";
import { ArrowLeft, FileQuestion, Send } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { usePortal } from "../portal-context";

const STATUS: Record<string, { label: string; tone: "neutral" | "info" | "accent" | "warning" | "success" | "danger" }> = {
  open: { label: "Open", tone: "neutral" }, reviewing: { label: "Reviewing", tone: "info" }, planned: { label: "Planned", tone: "accent" }, in_progress: { label: "In progress", tone: "warning" }, completed: { label: "Shipped", tone: "success" }, declined: { label: "Declined", tone: "danger" }, held: { label: "Under review", tone: "warning" },
};

export default function FeedbackItemPage() {
  const { itemId } = useParams();
  const { data: portal } = usePortal();
  const workspaceID = portal?.portal.workspace_id ?? "";
  const [body, setBody] = useState("");
  const item = useQuery<FeedbackItem>(["portal-feedback-item", workspaceID, itemId], (signal) => api.get(`/public/feedback/${encodeURIComponent(workspaceID)}/items/${encodeURIComponent(itemId ?? "")}`, { signal }), { enabled: Boolean(workspaceID && itemId) });
  const comments = useQuery<{ data: FeedbackComment[] }>(["portal-feedback-comments", workspaceID, itemId], (signal) => api.get(`/public/feedback/${encodeURIComponent(workspaceID)}/items/${encodeURIComponent(itemId ?? "")}/comments`, { signal }), { enabled: Boolean(workspaceID && itemId) });
  const addComment = useMutation<{ body: string }, FeedbackComment>((input) => api.post(`/public/feedback/${encodeURIComponent(workspaceID)}/items/${encodeURIComponent(itemId ?? "")}/comments`, input, { idempotencyKey: idempotencyKey() }), { invalidates: [["portal-feedback-item", workspaceID, itemId], ["portal-feedback-comments", workspaceID, itemId]], onSuccess: () => setBody("") });

  if (item.isLoading) return <p className="text-sm text-fg-muted">Loading feedback item…</p>;
  if (item.error || !item.data) return <EmptyState icon={FileQuestion} title="Feedback item unavailable" description={item.error instanceof ApiError ? item.error.message : "This request may have been removed or is not public."} />;
  const status = STATUS[item.data.status] ?? STATUS.open!;

  return <div className="mx-auto max-w-3xl space-y-5"><Link className="inline-flex items-center gap-2 text-sm text-fg-muted hover:text-fg" to="/feedback"><ArrowLeft className="size-4" />Back to feedback</Link><Card><CardBody><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold tracking-tight text-fg">{item.data.title}</h1><p className="mt-1 text-xs text-fg-muted">Submitted {formatDate(item.data.created_at)}</p></div><Badge tone={status.tone}>{status.label}</Badge></div><p className="mt-5 whitespace-pre-wrap text-sm leading-relaxed text-fg-secondary">{item.data.description || "No description was provided."}</p><div className="mt-5 flex items-center gap-3 text-xs text-fg-muted"><span>{item.data.vote_count} votes</span><span>{item.data.comment_count} comments</span></div></CardBody></Card><Card><CardBody className="p-0"><div className="border-b border-line-subtle px-4 py-3"><h2 className="text-sm font-medium text-fg">Discussion</h2></div>{comments.isLoading ? <p className="px-4 py-5 text-sm text-fg-muted">Loading comments…</p> : comments.error ? <p className="px-4 py-5 text-sm text-danger">Could not load comments. Please try again.</p> : (comments.data?.data ?? []).length === 0 ? <p className="px-4 py-5 text-sm text-fg-muted">No comments yet.</p> : <ul className="divide-y divide-line-subtle">{(comments.data?.data ?? []).map((comment) => <li key={comment.id} className="flex gap-3 px-4 py-4"><Avatar name={comment.author_name} size="sm" /><div className="min-w-0"><p className="text-xs font-medium text-fg">{comment.author_name || "Customer"}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-relaxed text-fg-secondary">{comment.body}</p><p className="mt-1 text-2xs text-fg-muted">{formatDate(comment.created_at)}</p></div></li>)}</ul>}<div className="border-t border-line-subtle p-4"><Textarea rows={3} value={body} onChange={(event) => setBody(event.target.value)} placeholder={portal?.viewer ? "Add to the discussion…" : "Sign in to comment on this request."} disabled={!portal?.viewer} /><div className="mt-2 flex items-center justify-between gap-3"><p className="text-xs text-danger">{addComment.error ? "Could not post your comment. Please try again." : ""}</p>{portal?.viewer ? <Button variant="primary" size="sm" loading={addComment.isPending} disabled={!body.trim()} leading={<Send />} onClick={() => void addComment.mutate({ body: body.trim() }).catch(() => {})}>Post comment</Button> : <Link className="text-sm text-accent-text hover:underline" to={`/sign-in?next=${encodeURIComponent(`/feedback/${itemId}`)}`}>Sign in to comment</Link>}</div></div></CardBody></Card></div>;
}
