import { readFileSync, writeFileSync } from "node:fs";

const inputPath = "embedded/openapi.json";
const outputPath = "web/shared/src/types/generated-api.ts";
const document = JSON.parse(readFileSync(inputPath, "utf8"));
const schemas = document.components?.schemas ?? {};
const requestBodies = document.components?.requestBodies ?? {};
const responses = document.components?.responses ?? {};
const methods = new Set(["get", "post", "put", "patch", "delete", "options", "head", "trace"]);

function refName(ref) {
  return ref?.startsWith("#/components/schemas/") ? ref.slice("#/components/schemas/".length) : null;
}

function resolveSchema(schema) {
  const name = refName(schema?.$ref);
  return name ? schemas[name] ?? {} : schema ?? {};
}

function literal(value) {
  return JSON.stringify(value);
}

function typeName(name) {
  return `Api${name}`;
}

function schemaType(schema, stack = new Set()) {
  if (!schema || Object.keys(schema).length === 0) return "unknown";
  if (schema.$ref) {
    const name = refName(schema.$ref);
    return name ? typeName(name) : "unknown";
  }
  if (schema.const !== undefined) return literal(schema.const);
  if (Array.isArray(schema.enum)) return schema.enum.map(literal).join(" | ") || "never";
  if (schema.oneOf || schema.anyOf) {
    const variants = schema.oneOf ?? schema.anyOf;
    return variants.map((item) => schemaType(item, stack)).join(" | ") || "unknown";
  }
  if (schema.allOf) {
    const pieces = schema.allOf.map((item) => schemaType(item, stack));
    if (schema.properties || schema.additionalProperties) {
      pieces.push(schemaType({
        type: "object",
        properties: schema.properties,
        required: schema.required,
        additionalProperties: schema.additionalProperties,
      }, stack));
    }
    return pieces.join(" & ") || "unknown";
  }
  if (Array.isArray(schema.type)) {
    return schema.type.map((type) => type === "null" ? "null" : schemaType({ ...schema, type }, stack)).join(" | ");
  }
  if (schema.type === "null") return "null";
  if (schema.type === "array") return `${schemaType(schema.items, stack)}[]`;
  if (schema.type === "object" || schema.properties || schema.additionalProperties) {
    const properties = schema.properties ?? {};
    const required = new Set(schema.required ?? []);
    const lines = Object.entries(properties).map(([key, value]) =>
      `  ${literal(key)}${required.has(key) ? "" : "?"}: ${schemaType(value, stack)};`,
    );
    if (schema.additionalProperties) {
      lines.push(`  [key: string]: ${schema.additionalProperties === true ? "unknown" : schemaType(schema.additionalProperties, stack)};`);
    }
    return lines.length ? `{\n${lines.join("\n")}\n}` : "Record<string, unknown>";
  }
  switch (schema.type) {
    case "string": return "string";
    case "integer":
    case "number": return "number";
    case "boolean": return "boolean";
    case "null": return "null";
    default: return "unknown";
  }
}

function resolveRequestSchema(operation) {
  const body = operation.requestBody;
  if (!body) return null;
  const bodyDefinition = body.$ref ? requestBodies[body.$ref.split("/").pop()] : body;
  return bodyDefinition?.content?.["application/json"]?.schema ?? null;
}

function resolveResponseSchema(operation) {
  const statuses = Object.keys(operation.responses ?? {})
    .filter((status) => /^2\d\d$/.test(status))
    .sort((a, b) => Number(a) - Number(b));
  const response = operation.responses?.[statuses[0]];
  if (!response) return null;
  const responseDefinition = response.$ref ? responses[response.$ref.split("/").pop()] : response;
  return responseDefinition?.content?.["application/json"]?.schema ?? null;
}

const operations = [];
for (const [path, pathItem] of Object.entries(document.paths ?? {})) {
  for (const [method, operation] of Object.entries(pathItem)) {
    if (!methods.has(method) || !operation?.operationId) continue;
    operations.push({
      id: operation.operationId,
      method: method.toUpperCase(),
      path,
      request: schemaType(resolveRequestSchema(operation)),
      response: schemaType(resolveResponseSchema(operation)),
    });
  }
}
operations.sort((a, b) => a.id.localeCompare(b.id));

const output = [
  "// Code generated by scripts/generate-ts-api.mjs from embedded/openapi.json. Do not edit.",
  "// Regenerate with: node scripts/generate-openapi.mjs && node scripts/generate-ts-api.mjs",
  "",
];

for (const [name, schema] of Object.entries(schemas).sort(([a], [b]) => a.localeCompare(b))) {
  output.push(`export type ${typeName(name)} = ${schemaType(resolveSchema(schema))};`, "");
}

output.push("export type ApiOperationId =", ...operations.map((operation, index) => `  | ${literal(operation.id)}${index === operations.length - 1 ? ";" : ""}`), "");
output.push("export type ApiOperationCatalog = {");
for (const operation of operations) {
  output.push(`  ${literal(operation.id)}: { method: ${literal(operation.method)}; path: ${literal(operation.path)}; request: ${operation.request}; response: ${operation.response}; };`);
}
output.push("};", "", "export type ApiRequest<TOperation extends ApiOperationId> = ApiOperationCatalog[TOperation][\"request\"];", "export type ApiResponse<TOperation extends ApiOperationId> = ApiOperationCatalog[TOperation][\"response\"];", "");

writeFileSync(outputPath, `${output.join("\n")}\n`);
console.log(`Generated ${Object.keys(schemas).length} API models and ${operations.length} operation entries.`);
